# Generated by Django 4.0.1 on 2022-02-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observingsession',
            options={'ordering': ['-utdt_start']},
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='dec_limit',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='hour_angle_range',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='mag_limit',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='session_length',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='show_planets',
        ),
        migrations.AddField(
            model_name='observingsession',
            name='utdt_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='UTDT End'),
        ),
    ]
