# Generated by Django 4.0.1 on 2022-02-02 21:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0017_remove_observinglocation_x_state'),
        ('session', '0002_alter_observingsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observingsession',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, help_text='1 (poor) to 5 (excellent)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Seeing'),
        ),
        migrations.AlterField(
            model_name='observingsession',
            name='location',
            field=models.ForeignKey(limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
