# Generated by Django 4.0.1 on 2022-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_observingsession_seeing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observingsession',
            name='cloud_cover',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cloud Cover'),
        ),
        migrations.AddField(
            model_name='observingsession',
            name='humidity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Humidity'),
        ),
        migrations.AddField(
            model_name='observingsession',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='observingsession',
            name='temperature',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperature'),
        ),
    ]
