# Generated by Django 4.0.1 on 2022-02-03 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_alter_observingsession_seeing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observingsession',
            options={},
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='cloud_cover',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='seeing',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='utdt_end',
        ),
        migrations.RemoveField(
            model_name='observingsession',
            name='utdt_start',
        ),
        migrations.CreateModel(
            name='ObservingCircumstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utdt', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='UTDT Start')),
                ('session_stage', models.CharField(blank=True, choices=[('start', 'Start'), ('during', 'During'), ('end', 'End')], max_length=20, null=True, verbose_name='Session Stage')),
                ('seeing', models.PositiveIntegerField(blank=True, choices=[(5, '5 = Excellent: stable diffraction rings'), (4, '4 = Good: light undulations across diffraction rings'), (3, '3 = Fair: broken diffraction rings; central disk deformations'), (2, '2 = Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, '1 = Fail: boiling image; no sign of diffraction pattern')], help_text='1 (poor) to 5 (excellent)', null=True, verbose_name='Seeing')),
                ('temperature', models.IntegerField(blank=True, null=True, verbose_name='Temperature')),
                ('humidity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Humidity')),
                ('cloud_cover', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cloud Cover')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.observingsession')),
            ],
            options={
                'ordering': ['utdt'],
            },
        ),
    ]
