# Generated by Django 4.0.1 on 2022-02-03 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_observingsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observingcircumstances',
            options={'ordering': ['utdt'], 'verbose_name': 'Conditions', 'verbose_name_plural': 'Observing Conditions'},
        ),
        migrations.AddField(
            model_name='observingsession',
            name='ut_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='UT Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observingcircumstances',
            name='cloud_cover',
            field=models.PositiveIntegerField(blank=True, help_text='in %', null=True, verbose_name='Cloud Cover'),
        ),
        migrations.AlterField(
            model_name='observingcircumstances',
            name='humidity',
            field=models.PositiveIntegerField(blank=True, help_text='in %', null=True, verbose_name='Humidity'),
        ),
        migrations.AlterField(
            model_name='observingcircumstances',
            name='temperature',
            field=models.IntegerField(blank=True, help_text='°F', null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='observingcircumstances',
            name='utdt',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='UTDT'),
        ),
    ]
