# Generated by Django 4.0.1 on 2022-02-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_alter_observingcircumstances_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observingcircumstances',
            name='sqm',
            field=models.FloatField(blank=True, null=True, verbose_name='SQM'),
        ),
    ]
