# Generated by Django 4.0.4 on 2022-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0012_alter_observingcircumstances_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observingsession',
            options={'ordering': ['-ut_date']},
        ),
        migrations.AddField(
            model_name='observingcircumstances',
            name='moon',
            field=models.BooleanField(default=False, verbose_name='Moon'),
        ),
    ]
