# Generated by Django 4.0.4 on 2022-07-31 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0013_alter_observingsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observingsession',
            options={'ordering': ['-ut_date', '-pk']},
        ),
    ]
