# Generated by Django 4.0.4 on 2022-08-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0015_observingcircumstances_use_sqm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observingcircumstances',
            name='session_stage',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('during', 'During'), ('end', 'End')], default='during', max_length=20, null=True, verbose_name='Session Stage'),
        ),
    ]
