# Generated by Django 4.2.19 on 2025-02-09 17:36

from django.db import migrations, models
import skytour.apps.astro.time


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_alter_observingcircumstances_session_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observingcircumstances',
            name='ut_datetime',
            field=models.DateTimeField(default=skytour.apps.astro.time.utc_now, verbose_name='UTDT'),
        ),
    ]
