
TIME_ZONES = {
    '-11:00': {'value': -11.0, 'abbr': 'MIT', 'name': 'Midway Islands Time'},
    '-10:00': {'value': -10.0, 'abbr': 'HST', 'name': 'Hawaii Standard Time'},
    '-09:00': {'value':  -9.0, 'abbr': 'AKST', 'name': 'Alaska Standard Time'},
    '-08:00': {'value':  -8.0, 'abbr': 'PST', 'name': 'Pacific Standard Time'},
    '-07:00': {'value':  -7.0, 'abbr': 'MST', 'name': 'Mountain Standard Time'},
    '-06:00': {'value':  -6.0, 'abbr': 'CST', 'name': 'Central Standard Time'},
    '-05:00': {'value':  -5.0, 'abbr': 'EST', 'name': 'Eastern Standard Time'},
    '-04:00': {'value':  -4.0, 'abbr': 'AST', 'name': 'Atlantic Standard Time'},
    '-03:30': {'value':  -3.5, 'abbr': 'NST', 'name': 'Newfoundland Standard Time'},
    '-03:00': {'value':  -3.0, 'abbr': 'AST', 'name': 'Atlantic Standard Time'},
    '-02:00': {'value':  -2.0, 'abbr': 'MAT', 'name': 'Mid-Atlantic Standard Time'},
    '-01:00': {'value':  -1.0, 'abbr': 'CVT', 'name': 'Cape Verde Time'},
    '+00:00': {'value':   0.0, 'abbr': 'GMT', 'name': 'Greenwich Mean Time'},
    '+01:00': {'value':   1.0, 'abbr': 'ETC', 'name': 'European Central Time'},
    '+02:00': {'value':   2.0, 'abbr': 'EET', 'name': 'Eastern European Time'},
    '+03:00': {'value':   3.0, 'abbr': 'EAT', 'name': 'Eastern African Time'},
    '+03:30': {'value':   3.5, 'abbr': 'MET', 'name': 'Middle East Time'},
    '+04:00': {'value':   4.0, 'abbr': 'NET', 'name': 'Near East Time'},
    '+05:00': {'value':   5.0, 'abbr': 'PLT', 'name': 'Pakistani Lahore Time'},
    '+05:30': {'value':   5.5, 'abbr': 'IST', 'name': 'India Standard Time'},
    '+06:00': {'value':   6.0, 'abbr': 'BST', 'name': 'Bangladesh Lahore Time'},
    '+07:00': {'value':   7.0, 'abbr': 'VST', 'name': 'Vietnam Standard Time'},
    '+08:00': {'value':   8.0, 'abbr': 'CTT', 'name': 'China Standard Time'},
    '+09:00': {'value':   9.0, 'abbr': 'JST', 'name': 'Japan Standard Time'},
    '+09:30': {'value':   9.5, 'abbr': 'ACT', 'name': 'Australia Central Time'},
    '+10:00': {'value':  10.0, 'abbr': 'AET', 'name': 'Australia Eastern Time'},
    '+11:00': {'value':  11.0, 'abbr': 'SST', 'name': 'Solomon Standard Time'},
    '+12:00': {'value':  12.0, 'abbr': 'FST', 'name': 'Fiji Standard Time'},
}
