# Generated by Django 4.0.1 on 2022-01-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_alter_telescope_aperture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eyepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='Plossi', max_length=50, null=True, verbose_name='Eyepiece Type')),
                ('focal_length', models.FloatField(help_text='mm', verbose_name='Focal Length')),
                ('apparent_fov', models.FloatField(default=52, help_text='degrees', verbose_name='App. FOV')),
            ],
        ),
        migrations.CreateModel(
            name='EyepieceTelescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyepiece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.eyepiece')),
                ('telescope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.telescope')),
            ],
        ),
        migrations.AddField(
            model_name='telescope',
            name='eyepieces',
            field=models.ManyToManyField(through='tech.EyepieceTelescope', to='tech.Eyepiece'),
        ),
    ]
