# Generated by Django 4.0.1 on 2022-01-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_alter_eyepiece_options_remove_telescope_eyepieces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EyepieceTelescope',
        ),
    ]
