# Generated by Django 4.0.1 on 2022-01-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_delete_eyepiecetelescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyepiece',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech.telescope'),
        ),
    ]
