# Generated by Django 4.0.2 on 2022-02-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_filter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='transmission',
            field=models.FloatField(blank=True, help_text='in %', null=True, verbose_name='Transmission'),
        ),
    ]
