# Generated by Django 4.0.2 on 2022-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_filter_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='dominant_wavelength',
            field=models.FloatField(blank=True, help_text='From Watten Specs, in nm', null=True, verbose_name='Dom. Wavelength'),
        ),
        migrations.AddField(
            model_name='filter',
            name='transmission_curve',
            field=models.ImageField(blank=True, null=True, upload_to='filter_specs', verbose_name='Trans. Curve'),
        ),
    ]
