# Generated by Django 4.0.2 on 2022-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_filter_dominant_wavelength_filter_transmission_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='tech_notes',
            field=models.TextField(blank=True, help_text='From Watten specs', null=True, verbose_name='Tech Notes'),
        ),
    ]
