# Generated by Django 4.0.2 on 2022-02-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0012_filter_watten_curve'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyepiece',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Short Name'),
        ),
        migrations.AddField(
            model_name='filter',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Short Name'),
        ),
    ]
