# Generated by Django 4.2.19 on 2025-02-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_eyepiece_short_name_filter_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='order_in_list',
            field=models.PositiveIntegerField(default=0, verbose_name='Order in List'),
        ),
    ]
