# Generated by Django 4.2.19 on 2025-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0014_telescope_order_in_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telescope',
            options={'ordering': ['order_in_list']},
        ),
    ]
