# Generated by Django 4.2.19 on 2025-02-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0015_alter_telescope_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Onboard camera', max_length=30, verbose_name='Sensor Name')),
                ('pixels_x', models.PositiveIntegerField(verbose_name='Pixels X')),
                ('pixels_y', models.PositiveIntegerField(verbose_name='Pixels Y')),
                ('pixel_size', models.FloatField(help_text='in microns: µm', verbose_name='Pixel Size')),
                ('telescope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tech.telescope')),
            ],
        ),
    ]
