# Generated by Django 4.2.19 on 2025-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0016_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='camera_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Camera Name'),
        ),
    ]
