# Generated by Django 4.2.19 on 2025-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0017_sensor_camera_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['order_in_list']},
        ),
        migrations.AddField(
            model_name='sensor',
            name='order_in_list',
            field=models.PositiveIntegerField(default=1, verbose_name='Order in List'),
        ),
    ]
