# Generated by Django 4.2.19 on 2025-02-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0018_alter_sensor_options_sensor_order_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='active',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, verbose_name='Active'),
        ),
    ]
