# Generated by Django 4.2.19 on 2025-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0019_telescope_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='active',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, help_text='If active will show up on drop-downs for telescopes', verbose_name='Active'),
        ),
    ]
