# Generated by Django 4.2.19 on 2025-03-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0020_alter_telescope_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
    ]
