# Generated by Django 4.2.19 on 2025-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0021_telescope_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='uses_eyepiece',
            field=models.BooleanField(default=False, help_text='False for Imaging/Smart Telescopes', verbose_name='Uses Eyepieces'),
        ),
    ]
