# Generated by Django 4.2.19 on 2025-04-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0022_telescope_uses_eyepiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='include_on_finder',
            field=models.BooleanField(default=True, help_text='Add FOV when creating finder charts', verbose_name='Include on Finder Charts'),
        ),
    ]
