# Generated by Django 4.2.19 on 2025-04-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0023_telescope_include_on_finder'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='stellarium_sensor',
            field=models.PositiveIntegerField(blank=True, help_text='in Stellarium, the Sensor #', null=True, verbose_name='Stellarium Sensor #'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='stellarium_telescope',
            field=models.PositiveIntegerField(blank=True, help_text='in Stellarium, the Telescope #', null=True, verbose_name='Stellarium Telescope #'),
        ),
    ]
