from django.urls import path
from .views import (
    AvailableDSOObjectsView,    
    DSODetailView, 
    DSOListView, 
    DSOListActiveDSOListView,
    DSOAdjustDSOListView,
    DSOCreateList,
    DSOListActiveView,
    DSOListDetailView,
    DSOListListView,
    DSOListPDFView,
    DSOObservationLogView,
    DSORealTimeView,
    DSOSearchView,
    DSOEditMetadataView,
    DSOManageExternalImageView,
    DSOManageLibraryImagePanelView,
    DSOObservationEditView,
    DSOObservingModeEditView,
    DSOWikiPopup,
    DSOInFieldWikiPopup
)
urlpatterns = (
    path('', DSOListView.as_view(), name='dso-list'),
    path('available', AvailableDSOObjectsView.as_view(), name='dso-available-objects'),
    path('create_dso_list', DSOCreateList.as_view(), name='dso-create-list'),
    path('list/<int:pk>', DSOListDetailView.as_view(), name='dsolist-detail'),
    path('active/dso', DSOListActiveDSOListView.as_view(), name='active-dsolist-dso'),
    path('list/adjustlist/<str:op>/<int:pk>', DSOAdjustDSOListView.as_view(), name='dsolist-adjust'),
    path('list/dsoactive', DSOListActiveView.as_view(), name='dsolist-active'),
    path('list/pdf/<int:pk>', DSOListPDFView.as_view(), name='dsolist-pdf'),
    path('list', DSOListListView.as_view(), name='dsolist-list'),
    path('mode/<int:pk>', DSOObservingModeEditView.as_view(), name='dso-edit-modes'),
    path('observation/edit/<int:pk>', DSOObservationEditView.as_view(), name='dso-observe-edit'),
    path('observe', DSOObservationLogView.as_view(), name='dso-observed'),
    path('real-time/<int:pk>', DSORealTimeView.as_view(), name='dso-real-time'),
    path('search', DSOSearchView.as_view(), name='dso-name-search'),
    path('edit/<int:pk>', DSOEditMetadataView.as_view(), name='dso-edit-metadata'),
    path('image/edit/<int:pk>',DSOManageExternalImageView.as_view(), name='dso-manage-image'),
    path('panel/edit/<str:panel>/<int:pk>', DSOManageLibraryImagePanelView.as_view(), name='dso-manage-panel'),
    path('wiki/<int:pk>', DSOWikiPopup.as_view(), name='dso-wiki-popup'),
    path('fieldwiki/<int:pk>', DSOInFieldWikiPopup.as_view(), name='dsoinfield-wiki-popup'),
    path('<int:pk>', DSODetailView.as_view(), name='dso-detail'),
)