# Generated by Django 3.2.9 on 2021-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Catalog Name')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=3, verbose_name='Abbreviation')),
                ('genitive', models.CharField(max_length=80, verbose_name='Genitive')),
            ],
        ),
    ]
