# Generated by Django 3.2.9 on 2021-11-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='use_abbr',
            field=models.BooleanField(default=True, verbose_name='Use Abbr in List'),
        ),
    ]
