# Generated by Django 3.2.9 on 2021-11-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_catalog_use_abbr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='constellation',
            options={'ordering': ['name']},
        ),
    ]
