# Generated by Django 3.2.9 on 2021-11-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_objecttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objecttype',
            options={'ordering': ['name']},
        ),
    ]
