# Generated by Django 3.2.9 on 2021-11-18 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_objecttype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['abbreviation']},
        ),
    ]
