# Generated by Django 3.2.9 on 2021-11-18 15:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_catalog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='bgcolor',
            field=colorfield.fields.ColorField(default='#666666', max_length=18, verbose_name='Background Color'),
        ),
    ]
