# Generated by Django 3.2.9 on 2021-11-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_objecttype_bgcolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constellation',
            options={'ordering': ['abbreviation']},
        ),
    ]
