# Generated by Django 4.0 on 2021-12-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_constellation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='marker_type',
            field=models.CharField(default='x', max_length=1, verbose_name='Plot Marker Type'),
        ),
    ]
