# Generated by Django 4.0.1 on 2022-01-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_constellation_map_constellation_other_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='background',
            field=models.TextField(blank=True, null=True, verbose_name='Background'),
        ),
    ]
