# Generated by Django 4.0.1 on 2022-01-17 19:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_constellation_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='background',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Background'),
        ),
    ]
