# Generated by Django 4.0.1 on 2022-01-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_alter_constellation_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='historical_image',
            field=models.ImageField(blank=True, null=True, upload_to='historical_constellation_maps', verbose_name='Historical Map'),
        ),
    ]
