# Generated by Django 4.0.1 on 2022-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_constellation_historical_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='map_symbol_type',
            field=models.CharField(choices=[('Marker', 'marker'), ('Ellipse', 'ellipse'), ('Open Circle', 'open-circle'), ('Gray Circle', 'gray circle'), ('Circle in Square', 'circle-in-square'), ('Open Square', 'square'), ('Gray Square', 'gray-square'), ('Circle in Gray Square', 'circle-in-gray-square')], default='marker', max_length=30, verbose_name='Map Symbol Type'),
        ),
    ]
