# Generated by Django 4.0.1 on 2022-01-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_alter_objecttype_map_symbol_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttype',
            name='marker_type',
            field=models.CharField(default='x', max_length=10, verbose_name='Plot Marker Type'),
        ),
    ]
