# Generated by Django 4.0.1 on 2022-01-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_alter_objecttype_marker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='marker_color',
            field=models.CharField(default='#999', max_length=7, verbose_name='Marker Type Color'),
        ),
    ]
