# Generated by Django 4.0.1 on 2022-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_objecttype_marker_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objecttype',
            name='map_symbol_type',
            field=models.CharField(choices=[('marker', 'Marker'), ('ellipse', 'Ellipse'), ('open-circle', 'Open Circle'), ('gray-circle', 'Gray Circle'), ('circle-square', 'Circle in Square'), ('square', 'Open Square'), ('gray-square', 'Gray Square'), ('circle-gray-square', 'Circle in Gray Square'), ('circle-plus', 'Circle Plus')], default='marker', max_length=30, verbose_name='Map Symbol Type'),
        ),
    ]
