# Generated by Django 4.0.1 on 2022-01-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_catalog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default='x', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
