# Generated by Django 4.0.2 on 2022-02-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_catalog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Abbr. Code'),
        ),
    ]
