# Generated by Django 4.0.2 on 2022-02-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_objecttype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='utils.Constellation'),
        ),
    ]
