# Generated by Django 4.0.2 on 2022-02-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_constellation_neighbors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='other_map',
            field=models.ImageField(blank=True, null=True, upload_to='constellation_maps', verbose_name='Other Map'),
        ),
    ]
