# Generated by Django 4.0.3 on 2022-03-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0025_alter_objecttype_map_symbol_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='objecttype',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Short Name'),
        ),
    ]
