# Generated by Django 4.0.4 on 2022-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0029_constellationboundaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellationboundaries',
            name='end_vertex',
            field=models.PositiveIntegerField(verbose_name='End Vertex'),
        ),
        migrations.AlterField(
            model_name='constellationboundaries',
            name='start_vertex',
            field=models.PositiveIntegerField(verbose_name='Start Vertex'),
        ),
    ]
