# Generated by Django 4.0.4 on 2023-12-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_alter_constellationboundaries_end_vertex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['abbreviation'], 'verbose_name': 'DSO Catalog', 'verbose_name_plural': 'DSO Catalogs'},
        ),
    ]
