# Generated by Django 4.0.4 on 2023-12-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0031_alter_catalog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='area',
            field=models.FloatField(default=0.0, help_text='sq. Deg.', verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constellation',
            name='center_dec',
            field=models.FloatField(default=0.0, verbose_name='Center Dec.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constellation',
            name='center_ra',
            field=models.FloatField(default=0.0, verbose_name='Center RA'),
            preserve_default=False,
        ),
    ]
