# Generated by Django 4.2.9 on 2024-01-04 22:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0032_constellation_area_constellation_center_dec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttype",
            name="bgcolor",
            field=colorfield.fields.ColorField(
                default="#666666",
                image_field=None,
                max_length=25,
                samples=None,
                verbose_name="Background Color",
            ),
        ),
    ]
