# Generated by Django 4.2.9 on 2024-08-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0035_alter_objecttype_map_symbol_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objecttype",
            name="map_symbol_type",
            field=models.CharField(
                choices=[
                    ("marker", "Marker"),
                    ("ellipse", "Ellipse"),
                    ("open-circle", "Open Circle"),
                    ("gray-circle", "Gray Circle"),
                    ("circle-square", "Circle in Square"),
                    ("square", "Open Square"),
                    ("gray-square", "Gray Square"),
                    ("circle-gray-square", "Circle in Gray Square"),
                    ("circle-plus", "Circle Plus"),
                    ("two-circles", "Double Circle"),
                    ("two-squares", "Two Squares"),
                ],
                default="marker",
                max_length=30,
                verbose_name="Map Symbol Type",
            ),
        ),
    ]
