# Generated by Django 4.2.9 on 2025-01-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0036_alter_objecttype_map_symbol_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="expected_complete",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                verbose_name="Expected Completed",
            ),
        ),
        migrations.AddField(
            model_name="starcatalog",
            name="expected_complete",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                verbose_name="Expected Completed",
            ),
        ),
    ]
