# Generated by Django 4.2.9 on 2025-01-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0037_catalog_expected_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="number_objects",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Might include missing/invalid objects",
                null=True,
                verbose_name="Number of Objects",
            ),
        ),
        migrations.AddField(
            model_name="starcatalog",
            name="number_objects",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Might include missing/invalid objects",
                null=True,
                verbose_name="Number of Objects",
            ),
        ),
    ]
