# Generated by Django 4.2.9 on 2025-01-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0038_catalog_number_objects_starcatalog_number_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalog",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="starcatalog",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="Notes"),
        ),
    ]
