# Generated by Django 4.2.19 on 2025-02-09 17:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0039_catalog_notes_starcatalog_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='description',
            field=models.TextField(blank=True, help_text='Can contain raw HTML', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='constellation',
            name='background',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Old Background'),
        ),
    ]
