# Generated by Django 4.2.19 on 2025-02-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0040_constellation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constellation',
            name='background',
        ),
    ]
