# Generated by Django 4.2.19 on 2025-02-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0041_remove_constellation_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='precedence',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 = Primary'), (2, '2 = Important'), (3, '3 = Secondary'), (4, '4 = Collection'), (5, '5 = Ancillary'), (6, '6 = Survey'), (7, '7 = Other'), (8, '8 = Incidental'), (9, '9 = Custom')], null=True, verbose_name='Precedence in Catalog Lists'),
        ),
        migrations.AddField(
            model_name='starcatalog',
            name='precedence',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 = Primary'), (2, '2 = Important'), (3, '3 = Secondary'), (4, '4 = Collection'), (5, '5 = Ancillary'), (6, '6 = Survey'), (7, '7 = Other'), (8, '8 = Incidental'), (9, '9 = Custom')], null=True, verbose_name='Precedence in Catalog Lists'),
        ),
    ]
