# Generated by Django 4.2.19 on 2025-02-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0042_catalog_precedence_starcatalog_precedence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ['precedence', 'abbreviation'], 'verbose_name': 'DSO Catalog', 'verbose_name_plural': 'DSO Catalogs'},
        ),
    ]
