# Generated by Django 4.2.19 on 2025-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0043_alter_catalog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormerConstellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=3, verbose_name='Slug')),
                ('source', models.TextField(blank=True, null=True, verbose_name='Source')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
            ],
        ),
    ]
