# Generated by Django 4.2.23 on 2025-06-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0045_formerconstellation_lookup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formerconstellation',
            name='lookup_name',
        ),
        migrations.AddField(
            model_name='catalog',
            name='lookup_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Lookup Name'),
        ),
        migrations.AddField(
            model_name='starcatalog',
            name='lookup_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Lookup Name'),
        ),
    ]
