# Generated by Django 4.2.23 on 2025-06-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0046_remove_formerconstellation_lookup_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='lookup_name',
        ),
        migrations.RemoveField(
            model_name='starcatalog',
            name='lookup_name',
        ),
    ]
