# Generated by Django 4.2.23 on 2025-06-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0047_remove_catalog_lookup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='lookup_mode',
            field=models.CharField(blank=True, choices=[('abbreivation', 'Abbreviation'), ('name', 'Catalog Name'), ('constellation', 'By Constellation')], default='abbreviation', help_text='for lookups like Wikipedia', max_length=40, null=True, verbose_name='Lookup Mode'),
        ),
    ]
