# Generated by Django 4.2.23 on 2025-06-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0051_constellationwiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='lookup_mode',
            field=models.CharField(choices=[('abbreviation', 'Abbreviation'), ('name', 'Catalog Name'), ('constellation', 'By Constellation'), ('other', 'Other Catalog'), ('custom', 'Custom')], default='abbreviation', help_text='for lookups like Wikipedia', max_length=40, verbose_name='Lookup Mode'),
        ),
    ]
