# Generated by Django 4.2.25 on 2026-01-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0052_alter_catalog_lookup_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='reverse_map',
            field=models.ImageField(blank=True, help_text='same as map but reversed colors', null=True, upload_to='constellation_maps', verbose_name='Reverse Map'),
        ),
        migrations.AddField(
            model_name='constellation',
            name='reverse_other_map',
            field=models.ImageField(blank=True, help_text='same as map but reversed colors', null=True, upload_to='constellation_maps', verbose_name='Reverse Other Map'),
        ),
    ]
