# Generated by Django 4.2.27 on 2026-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0053_constellation_reverse_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constellation',
            name='translation',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Translation'),
        ),
    ]
