# Generated by Django 3.2.9 on 2021-11-18 01:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_h', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA h')),
                ('ra_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='RA m')),
                ('ra_s', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='RA s')),
                ('dec_sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Sign')),
                ('dec_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='Dec °')),
                ('dec_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name="Dec '")),
                ('dec_s', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='Dec "')),
                ('separation', models.FloatField(help_text='Arcseconds', verbose_name='Ang. Sep')),
                ('magnitudes', models.CharField(help_text='comma separated', max_length=100, verbose_name='Magnitudes')),
                ('spectral_type', models.CharField(max_length=100, verbose_name='Spectral Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('constellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.constellation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_view', models.ImageField(upload_to='field_view/', verbose_name='Field View')),
                ('ra_h', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA h')),
                ('ra_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='RA m')),
                ('ra_s', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='RA s')),
                ('dec_sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Sign')),
                ('dec_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='Dec °')),
                ('dec_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name="Dec '")),
                ('dec_s', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='Dec "')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Vis. Magnitude')),
                ('angular_size', models.CharField(blank=True, help_text="single or double dimension, e.g., 8' by 12'", max_length=50, null=True, verbose_name='Angular Size')),
                ('surface_brightness', models.FloatField(blank=True, null=True, verbose_name='Surface Brightness')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.constellation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSOObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ut_date', models.DateField(help_text='UT Date', verbose_name='Date of Obs')),
                ('ut_time', models.TimeField(help_text='UT Time', verbose_name='Time of Obs')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='skyobject.dso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSOImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='object_image/', verbose_name='Image')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skyobject.dso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSOAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_catalog', models.CharField(max_length=24, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.catalog')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skyobject.dso')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleStarAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_catalog', models.CharField(max_length=24, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.catalog')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='skyobject.doublestar')),
            ],
        ),
    ]
