# Generated by Django 3.2.9 on 2021-11-18 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0002_auto_20211118_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublestar',
            name='dec_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='Dec "'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='ra_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='RA s'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='dec_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='Dec "'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='ra_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='RA s'),
        ),
    ]
