# Generated by Django 3.2.9 on 2021-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0003_auto_20211118_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoalias',
            options={'verbose_name': 'Alias', 'verbose_name_plural': 'Aliases'},
        ),
        migrations.AlterModelOptions(
            name='dsoimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='dso',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nickname'),
        ),
    ]
