# Generated by Django 3.2.9 on 2021-11-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0005_alter_dsoobservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='distance',
            field=models.FloatField(blank=True, help_text='ly', null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='field_view',
            field=models.ImageField(blank=True, null=True, upload_to='field_view/', verbose_name='Field View'),
        ),
    ]
