# Generated by Django 3.2.9 on 2021-11-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_objecttype_options'),
        ('skyobject', '0006_auto_20211118_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='object_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='utils.objecttype'),
            preserve_default=False,
        ),
    ]
