# Generated by Django 3.2.9 on 2021-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0011_auto_20211118_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dso',
            options={'ordering': ['ra', 'dec'], 'verbose_name': 'Deep Sky Object', 'verbose_name_plural': 'DSOs'},
        ),
    ]
