# Generated by Django 3.2.9 on 2021-11-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0016_auto_20211119_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoalias',
            name='shown_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shown Name'),
        ),
    ]
