# Generated by Django 3.2.9 on 2021-11-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0017_dsoalias_shown_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='amateur_image',
            field=models.NullBooleanField(default=None, verbose_name='Amateur Image'),
        ),
    ]
