# Generated by Django 3.2.9 on 2021-11-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0020_dso_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dso',
            name='priority',
            field=models.CharField(blank=True, choices=[('Highest', 'Highest'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True, verbose_name='Priority'),
        ),
    ]
