# Generated by Django 4.0 on 2021-12-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyobject', '0021_alter_dso_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='dso_finder_chart',
            field=models.ImageField(blank=True, null=True, upload_to='dso_finder_chart', verbose_name='DSO Finder Chart'),
        ),
    ]
