# Generated by Django 3.2.9 on 2021-11-18 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_auto_20211118_0157'),
        ('dso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dso',
            options={'verbose_name': 'Deep Sky Object', 'verbose_name_plural': 'DSOs'},
        ),
        migrations.AddField(
            model_name='dso',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.catalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dso',
            name='id_in_catalog',
            field=models.CharField(default=1, max_length=24, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
