# Generated by Django 3.2.9 on 2021-11-18 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0004_auto_20211118_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoobservation',
            options={'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
    ]
