# Generated by Django 3.2.9 on 2021-11-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0007_dso_object_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='contrast_index',
            field=models.FloatField(blank=True, null=True, verbose_name='Contrast Index'),
        ),
    ]
