# Generated by Django 3.2.9 on 2021-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0008_dso_contrast_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='distance_units',
            field=models.CharField(choices=[('ly', 'Light Year'), ('pc', 'Parsec'), ('Mpc', 'Megaparsec')], default='ly', max_length=10, verbose_name='Distance Unit'),
        ),
    ]
