# Generated by Django 3.2.9 on 2021-11-18 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0009_dso_distance_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='finder_chart',
            field=models.ImageField(blank=True, null=True, upload_to='finder_chart/', verbose_name='Finder Chart'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='dec_d',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='deg'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='dec_m',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='dec_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='dec_sign',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Dec: Sign'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='ra_h',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA: hr'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='ra_m',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='ra_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='dec_d',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='deg'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='dec_m',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='dec_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='dec_sign',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Dec: Sign'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='distance_units',
            field=models.CharField(choices=[('ly', 'Light Year'), ('kly', 'Kilo-Light Year'), ('pc', 'Parsec'), ('kpc', 'Kiloparsec'), ('Mpc', 'Megaparsec')], max_length=10, verbose_name='Distance Unit'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='ra_h',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA: hr'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='ra_m',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='ra_s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec'),
        ),
    ]
