# Generated by Django 3.2.9 on 2021-11-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0010_auto_20211118_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublestar',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='Dec.'),
        ),
        migrations.AddField(
            model_name='doublestar',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='R.A.'),
        ),
        migrations.AddField(
            model_name='dso',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='Dec.'),
        ),
        migrations.AddField(
            model_name='dso',
            name='ra',
            field=models.FloatField(blank=True, null=True, verbose_name='R.A.'),
        ),
    ]
