# Generated by Django 3.2.9 on 2021-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0012_alter_dso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='order_in_list',
            field=models.PositiveIntegerField(default=1, verbose_name='Order'),
        ),
    ]
