# Generated by Django 3.2.9 on 2021-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0013_dsoimage_order_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='shown_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shown Name'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='distance_units',
            field=models.CharField(choices=[('ly', 'Light Year'), ('kly', 'Kilo-Light Year'), ('Mly', 'Mega-Light Year'), ('pc', 'Parsec'), ('kpc', 'Kiloparsec'), ('Mpc', 'Megaparsec')], max_length=10, verbose_name='Distance Unit'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='magnitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Mag.'),
        ),
    ]
