# Generated by Django 3.2.9 on 2021-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0014_auto_20211118_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublestar',
            name='dec_text',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Dec. Text'),
        ),
        migrations.AddField(
            model_name='doublestar',
            name='ra_text',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='R.A. Text'),
        ),
        migrations.AddField(
            model_name='dso',
            name='dec_text',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Dec. Text'),
        ),
        migrations.AddField(
            model_name='dso',
            name='ra_text',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='R.A. Text'),
        ),
    ]
