# Generated by Django 3.2.9 on 2021-11-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0015_auto_20211118_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublestaralias',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='doublestaralias',
            name='object',
        ),
        migrations.AlterField(
            model_name='dso',
            name='distance_units',
            field=models.CharField(blank=True, choices=[('ly', 'Light Year'), ('kly', 'Kilo-Light Year'), ('Mly', 'Mega-Light Year'), ('pc', 'Parsec'), ('kpc', 'Kiloparsec'), ('Mpc', 'Megaparsec')], max_length=10, null=True, verbose_name='Distance Unit'),
        ),
        migrations.DeleteModel(
            name='DoubleStar',
        ),
        migrations.DeleteModel(
            name='DoubleStarAlias',
        ),
    ]
