# Generated by Django 3.2.9 on 2021-11-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0018_dsoimage_amateur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoimage',
            name='amateur_image',
            field=models.BooleanField(default=None, null=True, verbose_name='Amateur Image'),
        ),
    ]
