# Generated by Django 3.2.9 on 2021-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0019_alter_dsoimage_amateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True, verbose_name='Priority'),
        ),
    ]
