# Generated by Django 4.0.1 on 2022-01-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0022_dso_dso_finder_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dso',
            name='priority',
            field=models.CharField(blank=True, choices=[('Highest', 'Highest'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('None', 'None')], max_length=20, null=True, verbose_name='Priority'),
        ),
    ]
