# Generated by Django 4.0.1 on 2022-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0023_alter_dso_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='major_axis_size',
            field=models.FloatField(blank=True, help_text='arcmin', null=True, verbose_name='Size: Major Axis'),
        ),
        migrations.AddField(
            model_name='dso',
            name='minur_axis_size',
            field=models.FloatField(blank=True, help_text='arcmin', null=True, verbose_name='Size: Minor Axis'),
        ),
        migrations.AddField(
            model_name='dso',
            name='orientation_angle',
            field=models.PositiveIntegerField(blank=True, help_text='Degrees', null=True, verbose_name='Orientation Angle'),
        ),
    ]
