# Generated by Django 4.0.1 on 2022-01-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0024_dso_major_axis_size_dso_minur_axis_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dso',
            old_name='minur_axis_size',
            new_name='minor_axis_size',
        ),
    ]
