# Generated by Django 4.0.1 on 2022-02-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0027_alter_dsoobservation_seeing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsoobservation',
            name='seeing',
        ),
        migrations.RemoveField(
            model_name='dsoobservation',
            name='sqm',
        ),
    ]
