# Generated by Django 4.0.2 on 2022-02-09 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0028_remove_dsoobservation_seeing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsoobservation',
            name='ut_date',
        ),
        migrations.RemoveField(
            model_name='dsoobservation',
            name='ut_time',
        ),
        migrations.AddField(
            model_name='dsoobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='UT Date', verbose_name='Date of Obs'),
        ),
    ]
