# Generated by Django 4.0.2 on 2022-02-09 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0030_remove_dsoobservation_ut_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 18, 33, 160051), help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
            preserve_default=False,
        ),
    ]
