# Generated by Django 4.0.2 on 2022-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0031_dsoobservation_ut_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsoobservation',
            name='ut_date',
        ),
        migrations.RemoveField(
            model_name='dsoobservation',
            name='ut_time',
        ),
    ]
