# Generated by Django 4.0.2 on 2022-02-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_eyepiece_short_name_filter_short_name'),
        ('dso', '0035_alter_dsoobservation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoobservation',
            name='filters',
            field=models.ManyToManyField(to='tech.Filter'),
        ),
    ]
