# Generated by Django 4.0.2 on 2022-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0036_dsoobservation_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='morphological_type',
            field=models.CharField(blank=True, help_text='Gal Type, GC Class, etc.', max_length=20, null=True, verbose_name='Morphological Type'),
        ),
    ]
