# Generated by Django 4.0.2 on 2022-02-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0037_dso_morphological_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='show_on_skymap',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='Show on Skymap'),
        ),
    ]
