# Generated by Django 4.0.3 on 2022-03-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0038_dso_show_on_skymap'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='pdf_page',
            field=models.FileField(blank=True, null=True, upload_to='dso_pdf', verbose_name='PDF Page'),
        ),
    ]
