# Generated by Django 4.0.3 on 2022-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0039_dso_pdf_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ra_low', models.FloatField(blank=True, null=True, verbose_name='RA Low')),
                ('ra_high', models.FloatField(blank=True, null=True, verbose_name='RA High')),
                ('dso', models.ManyToManyField(to='dso.dso')),
            ],
        ),
    ]
