# Generated by Django 4.0.3 on 2022-04-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0040_dsolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsolist',
            name='ra_high',
        ),
        migrations.RemoveField(
            model_name='dsolist',
            name='ra_low',
        ),
    ]
