# Generated by Django 4.0.3 on 2022-04-10 18:40

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('dso', '0041_remove_dsolist_ra_high_remove_dsolist_ra_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsolist',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
