# Generated by Django 4.0.4 on 2022-04-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0043_dso_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsolist',
            name='add_to_plan',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, help_text='Set to YES/1 to add this to a PDF plan', verbose_name='Add to PDF Plan'),
        ),
    ]
