# Generated by Django 4.0.4 on 2022-04-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0044_dsolist_add_to_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dsolist',
            old_name='add_to_plan',
            new_name='show_on_plan',
        ),
    ]
