# Generated by Django 4.0.4 on 2022-04-16 15:11

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_starcatalog'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('dso', '0045_rename_add_to_plan_dsolist_show_on_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsolist',
            options={'verbose_name': 'DSO List', 'verbose_name_plural': 'DSO Lists'},
        ),
        migrations.AlterField(
            model_name='dsolist',
            name='show_on_plan',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, help_text='Set to YES/1 to add this to a PDF plan', verbose_name='On Plan PDF'),
        ),
        migrations.CreateModel(
            name='AtlasPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.PositiveIntegerField(verbose_name='Plate ID')),
                ('center_ra', models.FloatField(verbose_name='Center RA')),
                ('center_dec', models.FloatField(verbose_name='Center Dec')),
                ('plate', models.ImageField(upload_to='atlas_images', verbose_name='Plate')),
                ('constellation', models.ManyToManyField(to='utils.constellation')),
                ('dso', models.ManyToManyField(to='dso.dso')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
