# Generated by Django 4.0.4 on 2022-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0047_alter_atlasplate_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplate',
            name='plate_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Plate ID'),
        ),
    ]
