# Generated by Django 4.0.4 on 2022-04-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_starcatalog'),
        ('dso', '0049_alter_atlasplate_tags_alter_dsolist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplate',
            name='constellation',
            field=models.ManyToManyField(blank=True, to='utils.constellation'),
        ),
        migrations.AlterField(
            model_name='atlasplate',
            name='dso',
            field=models.ManyToManyField(blank=True, to='dso.dso'),
        ),
    ]
