# Generated by Django 4.0.4 on 2022-04-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0050_alter_atlasplate_constellation_alter_atlasplate_dso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlasplate',
            options={'ordering': ['plate_id'], 'verbose_name': 'Atlas Plate', 'verbose_name_plural': 'Atlas Plates'},
        ),
        migrations.AddField(
            model_name='atlasplate',
            name='slug',
            field=models.SlugField(default='x'),
            preserve_default=False,
        ),
    ]
