# Generated by Django 4.0.4 on 2022-04-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0051_alter_atlasplate_options_atlasplate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlasplate',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
