# Generated by Django 4.0.4 on 2022-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_eyepiece_short_name_filter_short_name'),
        ('dso', '0053_alter_dso_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoobservation',
            name='eyepieces',
            field=models.ManyToManyField(blank=True, to='tech.eyepiece'),
        ),
        migrations.AlterField(
            model_name='dsoobservation',
            name='filters',
            field=models.ManyToManyField(blank=-1, to='tech.filter'),
        ),
    ]
