# Generated by Django 4.0.4 on 2022-05-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0054_alter_dsoobservation_eyepieces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltasPlateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(choices=[('standard', 'Standard'), ('shapes', 'Shapes'), ('reversed', 'Reversed'), ('reversed-shapes', 'Reversed Shapes')], default='shapes', max_length=40, verbose_name='Version')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.atlasplate')),
            ],
        ),
    ]
