# Generated by Django 4.0.4 on 2022-05-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0055_altasplateversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='altasplateversion',
            name='version',
        ),
        migrations.AddField(
            model_name='altasplateversion',
            name='reversed',
            field=models.BooleanField(default=False, verbose_name='Reversed'),
        ),
        migrations.AddField(
            model_name='altasplateversion',
            name='shapes',
            field=models.BooleanField(default=False, verbose_name='Shapes'),
        ),
    ]
