# Generated by Django 4.0.4 on 2022-05-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0056_remove_altasplateversion_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altasplateversion',
            name='plate',
            field=models.ImageField(blank=True, null=True, upload_to='atlas_images', verbose_name='Plate'),
        ),
    ]
