# Generated by Django 4.0.4 on 2022-05-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0057_alter_altasplateversion_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='altasplateversion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='atlas_images', verbose_name='Plate'),
        ),
        migrations.AlterField(
            model_name='altasplateversion',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.atlasplate'),
        ),
    ]
