# Generated by Django 4.0.4 on 2022-05-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0058_altasplateversion_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AltasPlateVersion',
            new_name='AtlasPlateVersion',
        ),
    ]
