# Generated by Django 4.0.4 on 2022-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0059_rename_altasplateversion_atlasplateversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkyWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(help_text='1 to 5, 5 being the most intense', verbose_name='Level')),
                ('segment', models.PositiveIntegerField(verbose_name='Segment #')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('ra', models.FloatField(verbose_name='R.A. 2000')),
                ('dec', models.FloatField(verbose_name='Dec. 2000')),
            ],
        ),
    ]
