# Generated by Django 4.0.4 on 2022-05-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0060_milkyway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milkyway',
            old_name='level',
            new_name='contour',
        ),
    ]
