# Generated by Django 4.0.4 on 2022-05-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0061_rename_level_milkyway_contour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlasplate',
            name='plate',
        ),
    ]
