# Generated by Django 4.0.4 on 2022-05-20 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_alter_constellationboundaries_end_vertex_and_more'),
        ('dso', '0062_remove_atlasplate_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasPlateCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbor', models.PositiveIntegerField(verbose_name='Plate ID')),
                ('ra', models.FloatField(verbose_name='R.A.')),
                ('dec', models.FloatField(verbose_name='Dec.')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.atlasplate')),
            ],
        ),
        migrations.CreateModel(
            name='AtlasPlateConstellationAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.FloatField(verbose_name='R.A.')),
                ('dec', models.FloatField(verbose_name='Dec.')),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.constellation')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.atlasplate')),
            ],
        ),
    ]
