# Generated by Django 4.0.4 on 2022-06-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0019_observinglocation_pdf_form'),
        ('dso', '0063_atlasplatecrossreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlasplate',
            name='radius',
            field=models.FloatField(default=20.0, verbose_name='Radius'),
        ),
        migrations.AlterField(
            model_name='dsoobservation',
            name='location',
            field=models.ForeignKey(default=48, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
