# Generated by Django 4.0.4 on 2022-06-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0064_atlasplate_radius_alter_dsoobservation_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtlasPlateCrossReference',
        ),
    ]
