# Generated by Django 4.0.4 on 2022-07-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0065_delete_atlasplatecrossreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsolist',
            options={'ordering': ['-pk'], 'verbose_name': 'DSO List', 'verbose_name_plural': 'DSO Lists'},
        ),
        migrations.AlterField(
            model_name='dso',
            name='priority',
            field=models.CharField(blank=True, choices=[('Highest', '4 - Highest'), ('High', '3 - High'), ('Medium', '2 -Medium'), ('Low', '1 - Low'), ('None', '0 - None')], max_length=20, null=True, verbose_name='Priority'),
        ),
    ]
