# Generated by Django 4.0.4 on 2022-10-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_alter_observingcircumstances_session_stage'),
        ('dso', '0066_alter_dsolist_options_alter_dso_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoobservation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.observingsession'),
        ),
    ]
