# Generated by Django 4.0.4 on 2023-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0067_dsoobservation_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='exposure',
            field=models.FloatField(blank=True, null=True, verbose_name='Image Exposure'),
        ),
    ]
