# Generated by Django 4.0.4 on 2023-07-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0068_dsoimage_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='processing_status',
            field=models.CharField(blank=True, choices=[('None', 'Not Yet Started'), ('DB', 'Processed image added to DB'), ('Rejected', 'Image Rejected'), ('Unknown', 'Unknown')], max_length=30, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AddField(
            model_name='dsoobservation',
            name='imaging_status',
            field=models.IntegerField(choices=[(0, 'No Images'), (1, 'Image Taken'), (2, 'Multiple Images Taken')], default=0),
        ),
    ]
