# Generated by Django 4.0.4 on 2023-07-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0069_dsoimage_processing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoobservation',
            name='num_images',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
