# Generated by Django 4.0.4 on 2023-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0070_dsoobservation_num_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='own_image',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, verbose_name='My Own Image'),
        ),
    ]
