# Generated by Django 4.0.4 on 2023-07-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0071_dsoimage_own_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoobservation',
            name='imaging_status',
            field=models.IntegerField(blank=True, choices=[(0, 'No Images'), (1, 'Image Taken'), (2, 'Multiple Images Taken')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dsoobservation',
            name='num_images',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
