# Generated by Django 4.0.4 on 2023-08-06 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0073_dsolibraryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOImagingChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], null=True)),
                ('issues', models.CharField(blank=True, choices=[('lowdec', 'Low Declination'), ('angsize', 'Small Ang. Size'), ('dim', 'Low Surf. Brightness')], max_length=20, null=True, verbose_name='Potential Issues')),
                ('dso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.dso')),
            ],
        ),
    ]
