# Generated by Django 4.0.4 on 2023-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0074_dsoimagingchecklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoimagingchecklist',
            options={'ordering': ['-dso__dec'], 'verbose_name': 'Imaging Checklist DSO', 'verbose_name_plural': 'Imaging Checklist DSOs'},
        ),
        migrations.AlterModelOptions(
            name='dsolibraryimage',
            options={'verbose_name': 'DSO Library Images'},
        ),
        migrations.AlterField(
            model_name='dsoimagingchecklist',
            name='issues',
            field=models.CharField(blank=True, choices=[('lowdec', 'Low Declination'), ('angsize', 'Small Ang. Size'), ('dim', 'Low Surf. Brightness'), ('faint', 'Low V Magnitude'), ('questionable', 'Might not be possible')], max_length=20, null=True, verbose_name='Potential Issues'),
        ),
    ]
