# Generated by Django 4.0.4 on 2023-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0075_alter_dsoimagingchecklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='constructed_finder_chart_narrow',
            field=models.ImageField(blank=True, null=True, upload_to='con_finder_narrow', verbose_name='Constructed Finder Chart - Narrow'),
        ),
        migrations.AddField(
            model_name='dso',
            name='constructed_finder_chart_wide',
            field=models.ImageField(blank=True, null=True, upload_to='con_finder_wide', verbose_name='Constructed Finder Chart - Wide'),
        ),
    ]
