# Generated by Django 4.0.4 on 2023-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0076_dso_constructed_finder_chart_narrow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dso',
            name='constructed_finder_chart_narrow',
        ),
        migrations.RemoveField(
            model_name='dso',
            name='constructed_finder_chart_wide',
        ),
        migrations.AddField(
            model_name='dso',
            name='dso_finder_chart_narrow',
            field=models.ImageField(blank=True, null=True, upload_to='dso_finder_narrow', verbose_name='Constructed Finder Chart - Narrow'),
        ),
        migrations.AddField(
            model_name='dso',
            name='dso_finder_chart_wide',
            field=models.ImageField(blank=True, null=True, upload_to='dso_finder_wide', verbose_name='Constructed Finder Chart - Wide'),
        ),
    ]
