# Generated by Django 4.0.4 on 2023-08-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0077_remove_dso_constructed_finder_chart_narrow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoobservation',
            options={'ordering': ['-ut_datetime'], 'verbose_name': 'Observation', 'verbose_name_plural': 'Observations'},
        ),
        migrations.AddField(
            model_name='dsolist',
            name='pdf_page',
            field=models.FileField(blank=True, null=True, upload_to='dso_pdf', verbose_name='PDF Page'),
        ),
    ]
