# Generated by Django 4.0.4 on 2023-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0078_alter_dsoobservation_options_dsolist_pdf_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoimagingchecklist',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(-1, 'None'), (0, 'Lowest'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], null=True),
        ),
    ]
