# Generated by Django 4.0.4 on 2023-09-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0080_remove_dsoimage_amateur_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('e-crop', 'eQuinox 2: Cropped'), ('e-full', 'eQuinox 2: Full')], default=None, max_length=30, null=True, verbose_name='Image Type'),
        ),
        migrations.AddField(
            model_name='dsolibraryimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('e-crop', 'eQuinox 2: Cropped'), ('e-full', 'eQuinox 2: Full')], default=None, max_length=30, null=True, verbose_name='Image Type'),
        ),
    ]
