# Generated by Django 4.0.4 on 2023-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0081_dsoimage_image_type_dsolibraryimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='image_alterations',
            field=models.CharField(blank=True, choices=[('None', 'Raw'), ('annotated', 'Annotated'), ('processed', 'Processed')], default='None', max_length=30, null=True, verbose_name='Image Alterations'),
        ),
        migrations.AddField(
            model_name='dsolibraryimage',
            name='image_alterations',
            field=models.CharField(blank=True, choices=[('None', 'Raw'), ('annotated', 'Annotated'), ('processed', 'Processed')], default='None', max_length=30, null=True, verbose_name='Image Alterations'),
        ),
    ]
