# Generated by Django 4.0.4 on 2023-09-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0082_dsoimage_image_alterations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='dso_imaging_chart',
            field=models.ImageField(blank=True, null=True, upload_to='dso_imaging_charts', verbose_name='Imaging Chart for eQuinox 2'),
        ),
    ]
