# Generated by Django 4.0.4 on 2023-09-11 19:52

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_alter_constellationboundaries_end_vertex_and_more'),
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('dso', '0083_dso_dso_imaging_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasPlateSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.PositiveIntegerField(unique=True, verbose_name='Plate ID')),
                ('slug', models.SlugField(unique=True)),
                ('center_ra', models.FloatField(verbose_name='Center RA')),
                ('center_dec', models.FloatField(verbose_name='Center Dec')),
                ('radius', models.FloatField(default=20.0, verbose_name='Radius')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('constellation', models.ManyToManyField(blank=True, to='utils.constellation')),
                ('dso', models.ManyToManyField(blank=True, to='dso.dso')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtlasPlateSpecialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapes', models.BooleanField(default=False, verbose_name='Shapes')),
                ('reversed', models.BooleanField(default=False, verbose_name='Reversed')),
                ('image', models.ImageField(blank=True, null=True, upload_to='atlas_images_special', verbose_name='Plate')),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.atlasplatespecial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
