# Generated by Django 4.0.4 on 2023-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0084_atlasplatespecial_atlasplatespecialversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsolist',
            name='map_scaling_factor',
            field=models.FloatField(default=2.4, verbose_name='Map Scaling Factor'),
        ),
    ]
