# Generated by Django 4.0.4 on 2023-10-12 02:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0030_alter_constellationboundaries_end_vertex_and_more'),
        ('dso', '0085_dsolist_map_scaling_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_h', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA: hr')),
                ('ra_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('ra_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('ra', models.FloatField(blank=True, null=True, verbose_name='R.A.')),
                ('ra_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='R.A. Text')),
                ('dec_sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Dec: Sign')),
                ('dec_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='deg')),
                ('dec_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('dec_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('dec', models.FloatField(blank=True, null=True, verbose_name='Dec.')),
                ('dec_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='Dec. Text')),
                ('id_in_catalog', models.CharField(max_length=24, verbose_name='ID')),
                ('shown_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shown Name')),
                ('nickname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nickname')),
                ('morphological_type', models.CharField(blank=True, help_text='Gal Type, GC Class, etc.', max_length=20, null=True, verbose_name='Morphological Type')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Mag.')),
                ('angular_size', models.CharField(blank=True, help_text="single or double dimension, e.g., 8' by 12'", max_length=50, null=True, verbose_name='Angular Size')),
                ('surface_brightness', models.FloatField(blank=True, null=True, verbose_name='Surface Brightness')),
                ('contrast_index', models.FloatField(blank=True, null=True, verbose_name='Contrast Index')),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance')),
                ('distance_units', models.CharField(blank=True, choices=[('ly', 'Light Year'), ('kly', 'Kilo-Light Year'), ('Mly', 'Mega-Light Year'), ('pc', 'Parsec'), ('kpc', 'Kiloparsec'), ('Mpc', 'Megaparsec')], max_length=10, null=True, verbose_name='Distance Unit')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('orientation_angle', models.PositiveIntegerField(blank=True, help_text='Degrees', null=True, verbose_name='Orientation Angle')),
                ('major_axis_size', models.FloatField(blank=True, help_text='arcmin', null=True, verbose_name='Size: Major Axis')),
                ('minor_axis_size', models.FloatField(blank=True, help_text='arcmin', null=True, verbose_name='Size: Minor Axis')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.catalog')),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.constellation')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.objecttype')),
                ('parent_dso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.dso')),
            ],
            options={
                'verbose_name': 'Deep Sky Object in Field',
                'verbose_name_plural': 'Deep Sky Objects in Field',
                'ordering': ['ra', 'dec'],
            },
        ),
    ]
