# Generated by Django 4.0.4 on 2023-10-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0086_dsoinfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='map_label',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Map Label'),
        ),
        migrations.AddField(
            model_name='dsoinfield',
            name='map_label',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Map Label'),
        ),
    ]
