# Generated by Django 4.0.4 on 2023-12-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0089_dso_map_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dso',
            name='distance_units',
            field=models.CharField(blank=True, choices=[('ly', 'Light Year'), ('kly', 'Kilo-Light Year'), ('Mly', 'Mega-Light Year'), ('pc', 'Parsec'), ('kpc', 'Kiloparsec'), ('Mpc', 'Megaparsec'), ('z', 'Redshift')], max_length=10, null=True, verbose_name='Distance Unit'),
        ),
        migrations.AlterField(
            model_name='dsoinfield',
            name='distance_units',
            field=models.CharField(blank=True, choices=[('ly', 'Light Year'), ('kly', 'Kilo-Light Year'), ('Mly', 'Mega-Light Year'), ('pc', 'Parsec'), ('kpc', 'Kiloparsec'), ('Mpc', 'Megaparsec'), ('z', 'Redshift')], max_length=10, null=True, verbose_name='Distance Unit'),
        ),
    ]
