# Generated by Django 4.2.9 on 2024-01-14 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0093_dso_amateur_book_notes_dso_amateur_book_object_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dsoinfield",
            name="amateur_book_notes",
        ),
        migrations.RemoveField(
            model_name="dsoinfield",
            name="amateur_book_object",
        ),
        migrations.RemoveField(
            model_name="dsoinfield",
            name="book_skill",
        ),
    ]
