# Generated by Django 4.2.9 on 2024-03-10 17:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0096_dso_reimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="dso",
            name="metadata",
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="metadata",
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
