# Generated by Django 4.2.9 on 2024-03-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0097_dso_metadata_dsoinfield_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="dso",
            name="lookup_catalog",
            field=models.CharField(
                choices=[("leda", "HyperLeda"), ("simbad", "Simbad")],
                default="leda",
                max_length=10,
                verbose_name="Catalog for Lookup",
            ),
        ),
        migrations.AddField(
            model_name="dso",
            name="lookup_name_override",
            field=models.CharField(
                blank=True,
                help_text="Use the value to get data from external catalog",
                max_length=20,
                null=True,
                verbose_name="Name Override in Catalog Lookup",
            ),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="lookup_catalog",
            field=models.CharField(
                choices=[("leda", "HyperLeda"), ("simbad", "Simbad")],
                default="leda",
                max_length=10,
                verbose_name="Catalog for Lookup",
            ),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="lookup_name_override",
            field=models.CharField(
                blank=True,
                help_text="Use the value to get data from external catalog",
                max_length=20,
                null=True,
                verbose_name="Name Override in Catalog Lookup",
            ),
        ),
    ]
