# Generated by Django 4.2.9 on 2024-03-18 22:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0098_dso_lookup_catalog_dso_lookup_name_override_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dso",
            name="lookup_catalog",
        ),
        migrations.RemoveField(
            model_name="dso",
            name="lookup_name_override",
        ),
        migrations.RemoveField(
            model_name="dsoinfield",
            name="lookup_catalog",
        ),
        migrations.RemoveField(
            model_name="dsoinfield",
            name="lookup_name_override",
        ),
        migrations.AddField(
            model_name="dso",
            name="simbad",
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="simbad",
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
