# Generated by Django 4.2.9 on 2024-03-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0099_remove_dso_lookup_catalog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dso",
            name="hyperleda_name",
            field=models.CharField(
                blank=True,
                help_text="Use this name when querying HyperLeda",
                max_length=30,
                null=True,
                verbose_name="HyperLeda Name Override",
            ),
        ),
        migrations.AddField(
            model_name="dso",
            name="simbad_name",
            field=models.CharField(
                blank=True,
                help_text="Use this name when querying SIMBAD",
                max_length=30,
                null=True,
                verbose_name="SIMBAD Name Override",
            ),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="hyperleda_name",
            field=models.CharField(
                blank=True,
                help_text="Use this name when querying HyperLeda",
                max_length=30,
                null=True,
                verbose_name="HyperLeda Name Override",
            ),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="simbad_name",
            field=models.CharField(
                blank=True,
                help_text="Use this name when querying SIMBAD",
                max_length=30,
                null=True,
                verbose_name="SIMBAD Name Override",
            ),
        ),
    ]
