# Generated by Django 4.2.9 on 2024-03-21 23:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0100_dso_hyperleda_name_dso_simbad_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dso",
            name="archive_metadata",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dso",
            name="magnitude_system",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Mag. System"
            ),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="archive_metadata",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="magnitude_system",
            field=models.CharField(
                blank=True, max_length=3, null=True, verbose_name="Mag. System"
            ),
        ),
        migrations.AlterField(
            model_name="dso",
            name="metadata",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dso",
            name="simbad",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsoinfield",
            name="metadata",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dsoinfield",
            name="simbad",
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
