# Generated by Django 4.2.9 on 2024-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0102_alter_dsoimage_image_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsoimage",
            name="image_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("square", "Square Image"),
                    ("map", "Annotated Image"),
                    ("full", "Full Frame Image"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
                verbose_name="Image Class",
            ),
        ),
        migrations.AddField(
            model_name="dsolibraryimage",
            name="image_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("square", "Square Image"),
                    ("map", "Annotated Image"),
                    ("full", "Full Frame Image"),
                    ("other", "Other"),
                ],
                max_length=30,
                null=True,
                verbose_name="Image Class",
            ),
        ),
    ]
