# Generated by Django 4.2.9 on 2024-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0104_dsoimage_use_as_map_dsolibraryimage_use_as_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsoalias",
            name="alias_in_field",
            field=models.PositiveIntegerField(
                choices=[(0, "No"), (1, "Yes")],
                default=0,
                help_text="Alias is for a field object.",
                verbose_name="Alias in Field",
            ),
        ),
        migrations.AlterField(
            model_name="dsoimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                    ("s-crop", "Seestar S50: Cropped"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
        migrations.AlterField(
            model_name="dsolibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                    ("s-crop", "Seestar S50: Cropped"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
    ]
