# Generated by Django 4.2.9 on 2024-06-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0105_dsoalias_alias_in_field_alter_dsoimage_image_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsoalias",
            name="in_field_dso",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="In Field DSO Name"
            ),
        ),
    ]
