# Generated by Django 4.2.9 on 2024-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0106_dsoalias_in_field_dso"),
    ]

    operations = [
        migrations.AddField(
            model_name="dso",
            name="other_parameters",
            field=models.CharField(
                blank=True,
                help_text="Age, etc., in x: y; format",
                max_length=400,
                null=True,
                verbose_name="Other Params",
            ),
        ),
        migrations.AddField(
            model_name="dsoinfield",
            name="other_parameters",
            field=models.CharField(
                blank=True,
                help_text="Age, etc., in x: y; format",
                max_length=400,
                null=True,
                verbose_name="Other Params",
            ),
        ),
    ]
