# Generated by Django 4.2.9 on 2024-09-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0109_dsoinfieldalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsolist",
            name="active_observing_list",
            field=models.PositiveIntegerField(
                choices=[(0, "No"), (1, "Yes")], default=0, verbose_name="Active List"
            ),
        ),
    ]
