# Generated by Django 4.2.9 on 2025-01-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0110_dsolist_active_observing_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dsoinfield",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Deep Sky Object in Field",
                "verbose_name_plural": "Deep Sky Objects in Field",
            },
        ),
    ]
