# Generated by Django 4.2.19 on 2025-02-09 17:36

from django.db import migrations, models
import skytour.apps.astro.time


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0111_alter_dsoinfield_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=skytour.apps.astro.time.utc_now, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
    ]
