# Generated by Django 4.2.19 on 2025-02-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0113_remove_dso_archive_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsoobservation',
            name='imaging_status',
        ),
        migrations.RemoveField(
            model_name='dsoobservation',
            name='num_images',
        ),
    ]
