# Generated by Django 4.2.19 on 2025-02-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0114_remove_dsoobservation_imaging_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dso',
            name='show_on_skymap',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Filter for DSOs on skymap', verbose_name='Show on Skymap'),
        ),
        migrations.AlterField(
            model_name='dsoalias',
            name='alias_in_field',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Alias is for a field object.', verbose_name='Alias in Field'),
        ),
        migrations.AlterField(
            model_name='dsoinfieldalias',
            name='alias_in_field',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Alias is for a field object.', verbose_name='Alias in Field'),
        ),
        migrations.AlterField(
            model_name='dsolist',
            name='active_observing_list',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='This is used for a back-reference on lists of DSOs', verbose_name='Active List'),
        ),
        migrations.AlterField(
            model_name='dsolist',
            name='show_on_plan',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, help_text='Set to YES/1 to add this to a PDF plan', verbose_name='On Plan PDF'),
        ),
    ]
