# Generated by Django 4.2.19 on 2025-02-21 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0115_alter_dso_show_on_skymap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOObservingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('N', 'Naked Eye'), ('B', 'Binoculars'), ('S', 'Small Scope'), ('M', 'Medium Scope'), ('I', 'Imaging Scope')], max_length=10, verbose_name='Observing Mode')),
                ('viable', models.PositiveSmallIntegerField(choices=[(0, 'Not Viable'), (1, 'Unlikely Viable'), (2, 'Extreme Difficulty'), (3, '(Very) Difficult'), (4, 'Challenging'), (5, 'Requires Patience'), (6, 'Generally Visible'), (7, 'Usually Easy'), (8, 'Easy'), (9, 'Very Easy'), (10, 'Extremely easy')], verbose_name='Viability')),
                ('priority', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Lowest'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Highest')], null=True)),
                ('interesting', models.BooleanField(default=False)),
                ('challenging', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.dso')),
            ],
        ),
    ]
