# Generated by Django 4.2.9 on 2025-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0116_dsoobservingmode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dso",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Highest", "4 - Highest"),
                    ("High", "3 - High"),
                    ("Medium", "2 -Medium"),
                    ("Low", "1 - Low"),
                    ("Lowest", "0 - None"),
                ],
                help_text="DEPRECATED",
                max_length=20,
                null=True,
                verbose_name="Priority",
            ),
        ),
    ]
