# Generated by Django 4.2.9 on 2025-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso", "0117_alter_dso_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dso",
            name="override_metadata",
            field=models.BooleanField(
                default=False,
                help_text="Show model values for mag, angular size, etc. instead of Simbad/HyperLeda",
                verbose_name="Override Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="dsoinfield",
            name="override_metadata",
            field=models.BooleanField(
                default=False,
                help_text="Show model values for mag, angular size, etc. instead of Simbad/HyperLeda",
                verbose_name="Override Metadata",
            ),
        ),
    ]
