# Generated by Django 4.2.19 on 2025-02-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0118_alter_dso_override_metadata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DSOImagingChecklist',
        ),
    ]
