# Generated by Django 4.2.19 on 2025-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0120_alter_dsoimage_image_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsolist',
            name='dso',
            field=models.ManyToManyField(blank=True, to='dso.dso'),
        ),
    ]
