# Generated by Django 4.2.19 on 2025-03-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0121_alter_dsolist_dso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoimage',
            options={'ordering': ['order_in_list'], 'verbose_name': 'External Image', 'verbose_name_plural': 'External Images'},
        ),
    ]
