# Generated by Django 4.2.19 on 2025-03-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0122_alter_dsoimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dsoimage',
            name='exposure',
        ),
        migrations.RemoveField(
            model_name='dsoimage',
            name='image_alterations',
        ),
        migrations.RemoveField(
            model_name='dsoimage',
            name='image_style',
        ),
        migrations.RemoveField(
            model_name='dsoimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='dsoimage',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='dsoimage',
            name='use_as_map',
        ),
        migrations.RemoveField(
            model_name='dsoimage',
            name='use_in_carousel',
        ),
    ]
