# Generated by Django 4.2.19 on 2025-03-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0124_dsolibraryimage_image_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsolibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('landscape', 'Landscape'), ('portrait', 'Portait'), ('other', 'Other')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
    ]
