# Generated by Django 4.2.19 on 2025-03-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0126_remove_dsolibraryimage_image_alterations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoalias',
            options={'ordering': ['catalog__precedence'], 'verbose_name': 'Alias', 'verbose_name_plural': 'Aliases'},
        ),
        migrations.AlterModelOptions(
            name='dsoinfieldalias',
            options={'ordering': ['catalog__precedence'], 'verbose_name': 'Alias', 'verbose_name_plural': 'Aliases'},
        ),
        migrations.RemoveField(
            model_name='dsolibraryimage',
            name='image_style',
        ),
        migrations.RemoveField(
            model_name='dsolist',
            name='show_on_plan',
        ),
    ]
