# Generated by Django 4.2.19 on 2025-03-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0025_observinglocation_is_default_and_more'),
        ('dso', '0127_alter_dsoalias_options_alter_dsoinfieldalias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoobservation',
            name='location',
            field=models.ForeignKey(default=43, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
