# Generated by Django 4.2.19 on 2025-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0128_alter_dsoobservation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dso',
            name='show_on_simple_skymap',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Show on the simple SkyMap', verbose_name='Show on Simple SkyMap'),
        ),
        migrations.AlterField(
            model_name='dso',
            name='show_on_skymap',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Filter for DSOs on SkyMap', verbose_name='Show on SkyMap'),
        ),
    ]
