# Generated by Django 4.2.19 on 2025-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0129_dso_show_on_simple_skymap_alter_dso_show_on_skymap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsolibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('annotated', 'Annotated'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
    ]
