# Generated by Django 4.2.19 on 2025-04-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0130_alter_dsolibraryimage_image_processing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dsoobservingmode',
            options={'ordering': (models.Case(models.When(mode='N', then=models.Value(0)), models.When(mode='B', then=models.Value(1)), models.When(mode='S', then=models.Value(2)), models.When(mode='M', then=models.Value(3)), default=models.Value(4), output_field=models.IntegerField()),)},
        ),
    ]
