# Generated by Django 4.2.19 on 2025-04-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0131_alter_dsoobservingmode_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dso',
            name='field_view',
        ),
    ]
