# Generated by Django 4.2.19 on 2025-06-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0132_remove_dso_field_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoimage',
            name='caption',
            field=models.TextField(blank=True, null=True, verbose_name='Caption'),
        ),
    ]
