# Generated by Django 4.2.23 on 2025-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0133_dsoimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsolibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('mosaic', 'Mosaic'), ('landscape', 'Landscape'), ('portrait', 'Portait'), ('other', 'Other')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
    ]
