# Generated by Django 4.2.23 on 2025-06-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0134_alter_dsolibraryimage_image_orientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOInFieldWiki',
            fields=[
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wiki', serialize=False, to='dso.dsoinfield')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DSOWiki',
            fields=[
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wiki', serialize=False, to='dso.dso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
