# Generated by Django 4.2.25 on 2025-12-30 21:50

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('observe', '0025_observinglocation_is_default_and_more'),
        ('dso', '0135_dsoinfieldwiki_dsowiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoinfield',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='dsoobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
