# Generated by Django 4.2.25 on 2026-01-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0137_annalsdeepskydso'),
    ]

    operations = [
        migrations.AddField(
            model_name='annalsdeepskydso',
            name='byline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
