# Generated by Django 4.2.27 on 2026-02-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0138_annalsdeepskydso_byline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annalsdeepskydso',
            name='dso_in_field',
        ),
        migrations.CreateModel(
            name='AnnalsDeepSkyDSOInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField()),
                ('other_ref', models.CharField(blank=True, help_text='format: VV:PPP, VV:PPP, etc.', max_length=200, null=True)),
                ('byline', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annals', to='dso.dsoinfield')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
