# Generated by Django 4.2.27 on 2026-03-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0139_remove_annalsdeepskydso_dso_in_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSOObservingNotesSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dsolist',
            options={'ordering': ['-active_observing_list', '-pk'], 'verbose_name': 'DSO List', 'verbose_name_plural': 'DSO Lists'},
        ),
        migrations.CreateModel(
            name='DSOObservingNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('dso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.dso')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dso.dsoobservingnotessource')),
            ],
        ),
    ]
