# Generated by Django 4.2.27 on 2026-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0140_dsoobservingnotessource_alter_dsolist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoobservingnotes',
            name='page',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Page'),
        ),
        migrations.AddField(
            model_name='dsoobservingnotes',
            name='volume',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Volume'),
        ),
    ]
