# Generated by Django 4.2.27 on 2026-03-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0141_dsoobservingnotes_page_dsoobservingnotes_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsoobservingnotessource',
            name='symbol',
            field=models.CharField(default=' ', max_length=1, verbose_name='Symbol'),
        ),
    ]
