# Generated by Django 4.2.27 on 2026-03-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso', '0142_dsoobservingnotessource_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsoobservingnotessource',
            name='symbol',
            field=models.CharField(default=' ', max_length=4, verbose_name='Symbol'),
        ),
    ]
