# Generated by Django 4.0 on 2021-12-24 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0010_objecttype_marker_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_h', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA: hr')),
                ('ra_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('ra_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('ra', models.FloatField(blank=True, null=True, verbose_name='R.A.')),
                ('ra_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='R.A. Text')),
                ('dec_sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Dec: Sign')),
                ('dec_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='deg')),
                ('dec_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('dec_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('dec', models.FloatField(blank=True, null=True, verbose_name='Dec.')),
                ('dec_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='Dec. Text')),
                ('hr_id', models.PositiveIntegerField(verbose_name='HR #')),
                ('bayer', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bayer')),
                ('flamsteed', models.CharField(blank=True, max_length=10, null=True, verbose_name='Flamsteed')),
                ('constellation', models.CharField(blank=True, max_length=3, null=True, verbose_name='Constellation')),
                ('bd_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='BD #')),
                ('hd_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='HD #')),
                ('sao_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='SAO #')),
                ('fk5_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='FK5 #')),
                ('double_star', models.CharField(blank=True, max_length=1, null=True, verbose_name='Double Star Code')),
                ('ads_id', models.CharField(blank=True, max_length=5, null=True, verbose_name='ADS Designation')),
                ('var_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='Var. Star ID')),
                ('gal_long', models.FloatField(blank=True, null=True, verbose_name='Gal. Long.')),
                ('gal_lat', models.FloatField(blank=True, null=True, verbose_name='Gal. Lat.')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='V Mag.')),
                ('b_v', models.FloatField(blank=True, null=True, verbose_name='B-V')),
                ('u_b', models.FloatField(blank=True, null=True, verbose_name='U-B')),
                ('r_i', models.FloatField(blank=True, null=True, verbose_name='R-I')),
                ('spectral_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Spectral Type')),
                ('spt_code', models.CharField(blank=True, max_length=1, null=True, verbose_name='Sp. Type Code')),
                ('pm_ra', models.FloatField(blank=True, null=True, verbose_name='Prop. Motion RA')),
                ('pm_dec', models.FloatField(blank=True, null=True, verbose_name='Prop. Motion Dec.')),
                ('parallax_flag', models.CharField(blank=True, max_length=1, null=True, verbose_name='Parallax Flag')),
                ('parallax', models.FloatField(blank=True, null=True, verbose_name='Parallax')),
                ('radial_velocity', models.FloatField(blank=True, null=True, verbose_name='Radial Velocity')),
                ('rv_flag', models.CharField(blank=True, max_length=1, null=True, verbose_name='RV Flag')),
                ('rot_flag', models.CharField(blank=True, max_length=2, null=True, verbose_name='Rot. Vel. Flag')),
                ('vsini', models.PositiveIntegerField(blank=True, null=True, verbose_name='v sin i')),
                ('d_mag', models.FloatField(blank=True, null=True, verbose_name='d Mag (double)')),
                ('ang_sep', models.FloatField(blank=True, null=True, verbose_name='Ang. Sep.')),
                ('notes', models.BooleanField(default=False, verbose_name='Notes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubleStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_h', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA: hr')),
                ('ra_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('ra_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('ra', models.FloatField(blank=True, null=True, verbose_name='R.A.')),
                ('ra_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='R.A. Text')),
                ('dec_sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Dec: Sign')),
                ('dec_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='deg')),
                ('dec_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('dec_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('dec', models.FloatField(blank=True, null=True, verbose_name='Dec.')),
                ('dec_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='Dec. Text')),
                ('separation', models.FloatField(help_text='Arcseconds', verbose_name='Ang. Sep')),
                ('magnitudes', models.CharField(help_text='comma separated', max_length=100, verbose_name='Magnitudes')),
                ('spectral_type', models.CharField(max_length=100, verbose_name='Spectral Type')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('constellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.constellation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoubleStarAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_catalog', models.CharField(max_length=24, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.catalog')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stars.doublestar')),
            ],
        ),
    ]
