# Generated by Django 4.0.1 on 2022-01-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_brightstar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstar',
            name='proper_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proper Name'),
        ),
    ]
