# Generated by Django 4.0.1 on 2022-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_brightstar_proper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstar',
            name='name_explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Name Explanation'),
        ),
    ]
