# Generated by Django 4.0.4 on 2022-04-15 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0027_starcatalog'),
        ('stars', '0004_brightstar_name_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublestar',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utils.starcatalog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doublestar',
            name='distance',
            field=models.FloatField(blank=True, help_text='light years', null=True, verbose_name='Distance'),
        ),
        migrations.AddField(
            model_name='doublestar',
            name='id_in_catalog',
            field=models.CharField(default=1, max_length=24, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doublestar',
            name='shown_name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Shown Name'),
        ),
        migrations.AlterField(
            model_name='doublestaralias',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.starcatalog'),
        ),
    ]
