# Generated by Django 4.0.4 on 2023-12-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0006_variablestar_variablestaralias_stellarobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablestar',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
