# Generated by Django 4.0.4 on 2023-12-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0007_variablestar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablestar',
            name='mag_min1_amplitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Min 1 Amplitude'),
        ),
    ]
