# Generated by Django 4.0.4 on 2023-12-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0008_alter_variablestar_mag_min1_amplitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablestar',
            name='mag_min2_amplitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Min 2 Amplitude'),
        ),
    ]
