# Generated by Django 4.0.4 on 2023-12-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0009_alter_variablestar_mag_min2_amplitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablestar',
            name='bsc_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stars.brightstar'),
        ),
    ]
