# Generated by Django 4.0.4 on 2023-12-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0010_alter_variablestar_bsc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablestar',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
