# Generated by Django 4.2.25 on 2025-10-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0011_variablestar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleStarElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.FloatField(help_text='years', verbose_name='Orbital Period')),
                ('periastron', models.FloatField(help_text='year', verbose_name='Periastron Passage')),
                ('semimajor_axis', models.FloatField(help_text='arcsec', verbose_name='Semi-Major Axis')),
                ('eccentricity', models.FloatField(verbose_name='Eccentricity')),
                ('inclination', models.FloatField(help_text='degrees', verbose_name='Inclination')),
                ('ascending_node', models.FloatField(help_text='degrees', verbose_name='Ascending Node')),
                ('argument', models.FloatField(help_text='degrees', verbose_name='Argument of Periastron')),
                ('object', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='stars.doublestar')),
            ],
        ),
    ]
