# Generated by Django 4.2.25 on 2025-10-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0012_doublestarelements'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublestar',
            name='components',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Components'),
        ),
        migrations.AlterField(
            model_name='doublestar',
            name='separation',
            field=models.FloatField(blank=True, help_text='Arcseconds', null=True, verbose_name='Ang. Sep'),
        ),
    ]
