# Generated by Django 4.2.25 on 2025-10-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0013_doublestar_components_alter_doublestar_separation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableStarTypeOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('prototype', models.CharField(blank=True, max_length=40, null=True, verbose_name='Prototype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableStarTypeRevised',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Code')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('prototype', models.CharField(blank=True, max_length=40, null=True, verbose_name='Prototype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
