# Generated by Django 4.2.25 on 2025-10-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0014_variablestartypeoriginal_variablestartyperevised'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablestartypeoriginal',
            name='type_class',
            field=models.CharField(choices=[('erupt', 'Eruptive'), ('pulse', 'Pulsating'), ('rotate', 'Rotating'), ('cataclysmic', 'Cataclysmic (Explosive and Novalike'), ('eclipse', 'Eclipsing'), ('x-ray', 'Intense X-Ray Sources'), ('other', 'Other')], default='other', max_length=100, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variablestartyperevised',
            name='type_class',
            field=models.CharField(choices=[('erupt', 'Eruptive'), ('pulse', 'Pulsating'), ('rotate', 'Rotating'), ('cataclysmic', 'Cataclysmic (Explosive and Novalike'), ('eclipse', 'Eclipsing'), ('x-ray', 'Intense X-Ray Sources'), ('other', 'Other')], default='other', max_length=100, verbose_name='Class'),
            preserve_default=False,
        ),
    ]
