# Generated by Django 4.2.25 on 2025-10-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0015_variablestartypeoriginal_type_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablestartypeoriginal',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='variablestartyperevised',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Description'),
        ),
    ]
