# Generated by Django 4.2.25 on 2025-10-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0016_variablestartypeoriginal_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablestartypeoriginal',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='variablestartyperevised',
            name='short_description',
        ),
        migrations.AddField(
            model_name='variablestartypeoriginal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='variablestartyperevised',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
