# Generated by Django 4.2.25 on 2025-10-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0017_remove_variablestartypeoriginal_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablestartypeoriginal',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='variablestartyperevised',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Description'),
        ),
    ]
