# Generated by Django 4.2.25 on 2025-11-01 18:58

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0018_variablestartypeoriginal_short_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablestartypeoriginal',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='variablestartyperevised',
            options={'ordering': ['pk']},
        ),
        migrations.CreateModel(
            name='ObservableVariableStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_chart', models.ImageField(blank=True, help_text='AAVSO Finder Chart', null=True, upload_to='aavso_finder_chart', verbose_name='AAVSO Finder Chart')),
                ('finder_chart_mag', models.FloatField(default=14.5, verbose_name='Finder Limiting Mag')),
                ('finder_chart_fov', models.FloatField(default=60.0, help_text='(arcmin)', verbose_name='Finder Char FOV')),
                ('finder_json', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Finder JSON')),
                ('gcvs', models.OneToOneField(blank=True, help_text='link to GCVS record', null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.variablestar')),
            ],
        ),
    ]
