# Generated by Django 4.2.25 on 2025-11-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0019_alter_variablestartypeoriginal_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservableVariableStars',
            new_name='ObservableVariableStar',
        ),
    ]
