# Generated by Django 4.2.25 on 2025-11-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0020_rename_observablevariablestars_observablevariablestar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableStarLightCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='variable_star_light_curves', verbose_name='Image Field')),
                ('order_by', models.PositiveIntegerField(default=10, verbose_name='Order in List')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date Start')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date End')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.variablestar')),
            ],
        ),
    ]
