# Generated by Django 4.2.25 on 2025-11-02 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0021_variablestarlightcurve'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableStarNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('gcvs', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.variablestar')),
            ],
        ),
    ]
