# Generated by Django 4.2.25 on 2026-01-03 22:06

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('stars', '0024_brightstar_tags_doublestar_tags_variablestar_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='StellarObjectWiki',
            fields=[
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wiki', serialize=False, to='stars.stellarobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='distance',
            field=models.FloatField(blank=True, help_text='light years', null=True, verbose_name='Distance'),
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='magnitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Magnitude'),
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Shown Name'),
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='spectral_type',
            field=models.CharField(default='', max_length=100, verbose_name='Spectral Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
