# Generated by Django 4.2.25 on 2026-01-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0025_stellarobjectwiki_stellarobject_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellarobject',
            name='id_in_catalog',
            field=models.CharField(default='', max_length=24, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stellarobject',
            name='other_parameters',
            field=models.TextField(blank=True, help_text='Age, etc., in x: y; format - see README', null=True, verbose_name='Other Params'),
        ),
        migrations.AlterField(
            model_name='stellarobject',
            name='name',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Name'),
        ),
    ]
