# Generated by Django 4.2.25 on 2026-01-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0026_stellarobject_id_in_catalog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brightstar',
            old_name='constellation',
            new_name='constellation_string',
        ),
    ]
