# Generated by Django 4.2.25 on 2026-01-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0052_alter_catalog_lookup_mode'),
        ('stars', '0027_rename_constellation_brightstar_constellation_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstar',
            name='constellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.constellation'),
        ),
    ]
