# Generated by Django 4.2.25 on 2026-01-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0028_brightstar_constellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brightstar',
            name='constellation_string',
        ),
    ]
