# Generated by Django 4.2.25 on 2026-01-09 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0029_remove_brightstar_constellation_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightStarMetadata',
            fields=[
                ('star', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='stars.brightstar')),
                ('metadata', models.JSONField(blank=True, help_text='JSON object constructed from SIMBAD lookup', null=True)),
            ],
        ),
    ]
