# Generated by Django 4.2.25 on 2026-01-10 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0030_brightstarmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StellarObjectMetadata',
            fields=[
                ('star', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='stars.stellarobject')),
                ('simbad_lookup', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='JSON object constructed from SIMBAD lookup', null=True)),
            ],
        ),
    ]
