# Generated by Django 4.2.25 on 2026-01-10 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0031_stellarobjectmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightStarNotes',
            fields=[
                ('star', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='texts', serialize=False, to='stars.brightstar')),
                ('description', models.TextField(blank=True, null=True)),
                ('other_parameters', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
