# Generated by Django 4.2.25 on 2026-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0032_brightstarnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstarnotes',
            name='bsc_notes',
            field=models.TextField(blank=True, null=True, verbose_name='BSC Notes'),
        ),
    ]
