# Generated by Django 4.2.25 on 2026-01-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0033_brightstarnotes_bsc_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brightstar',
            old_name='notes',
            new_name='note_flag',
        ),
    ]
