# Generated by Django 4.2.25 on 2026-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0034_rename_notes_brightstar_note_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brightstarnotes',
            name='bsc_notes',
            field=models.JSONField(blank=True, null=True, verbose_name='BSC Notes'),
        ),
    ]
