# Generated by Django 4.2.25 on 2026-01-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0035_alter_brightstarnotes_bsc_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstar',
            name='ads_components',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Components'),
        ),
    ]
