# Generated by Django 4.2.25 on 2026-01-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0036_brightstar_ads_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstar',
            name='other_bayer',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Other Bayer'),
        ),
    ]
