# Generated by Django 4.2.25 on 2026-01-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0037_brightstar_other_bayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstar',
            name='other_constellation_name',
            field=models.CharField(blank=True, help_text='For stars that changed constellations when the IAU set boundaries', max_length=20, null=True, verbose_name='Other Constellation Name'),
        ),
    ]
