# Generated by Django 4.2.25 on 2026-01-17 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0038_brightstar_other_constellation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnalsDeepSkyStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField()),
                ('page', models.PositiveIntegerField()),
                ('other_ref', models.CharField(blank=True, help_text='format: VV:PPP, VV:PPP, etc.', max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bright_star', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annals', to='stars.brightstar')),
                ('double_star', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annals', to='stars.doublestar')),
                ('other_star', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annals', to='stars.stellarobject')),
                ('variable_star', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annals', to='stars.variablestar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
