# Generated by Django 4.2.25 on 2026-01-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0039_annalsdeepskystar'),
    ]

    operations = [
        migrations.AddField(
            model_name='stellarobject',
            name='proper_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
