# Generated by Django 4.2.25 on 2026-01-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0040_stellarobject_proper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='observablevariablestar',
            name='variable_star',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active', to='stars.variablestar'),
        ),
    ]
