# Generated by Django 4.2.25 on 2026-01-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0041_observablevariablestar_variable_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observablevariablestar',
            name='variable_star',
        ),
    ]
