# Generated by Django 4.2.25 on 2026-01-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0042_remove_observablevariablestar_variable_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='brightstarnotes',
            name='byline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
