# Generated by Django 4.2.25 on 2026-01-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0043_brightstarnotes_byline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brightstarnotes',
            name='byline',
        ),
        migrations.AddField(
            model_name='annalsdeepskystar',
            name='byline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
