# Generated by Django 4.2.27 on 2026-03-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0044_remove_brightstarnotes_byline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annalsdeepskystar',
            options={'ordering': ['-volume', '-page']},
        ),
    ]
