# Generated by Django 3.2.9 on 2021-11-26 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(choices=[('CT', 'Connecticut'), ('MA', 'Massachusetts'), ('ME', 'Maine'), ('NH', 'New Hampshire'), ('NY', 'New York')], default='MA', max_length=2, verbose_name='State')),
                ('primary_user', models.CharField(choices=[('Bob', 'Bob Donahue'), ('Rick', 'Rick Costello')], default='Bob', max_length=20, verbose_name='Primary User')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('elevation', models.FloatField(help_text='meters', verbose_name='Elevation')),
                ('sqm', models.FloatField(blank=True, help_text='mag/arcsec^2', null=True, verbose_name='SQM')),
                ('brightness', models.FloatField(blank=True, help_text='mcd/m^2', null=True, verbose_name='Brightness')),
                ('artificial_brightness', models.FloatField(help_text='µcd/m^2', verbose_name='Artif. Brightness')),
                ('bortle', models.PositiveIntegerField(verbose_name='Bortle Scale')),
                ('parking', models.CharField(blank=True, max_length=200, null=True, verbose_name='Parking Available')),
                ('is_flat', models.BooleanField(null=True, verbose_name='Is Flat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('light_sources', models.TextField(blank=True, null=True, verbose_name='Light Sources')),
                ('horizon_blockage', models.TextField(blank=True, help_text='describe cardinal directions with approximate altitude blocked, and/or other issues (buildings, etc.)', null=True, verbose_name='Horizon Blockage')),
            ],
        ),
        migrations.CreateModel(
            name='DistanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(choices=[('Bob', 'Bob Donahue'), ('Rick', 'Rick Costello')], default='Bob', max_length=20, verbose_name='User')),
                ('travel_distance', models.FloatField(blank=True, null=True, verbose_name='Travel Distance')),
                ('travel_time', models.FloatField(blank=True, help_text='minutes', null=True, verbose_name='Travel Time')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation')),
            ],
        ),
    ]
