# Generated by Django 3.2.9 on 2021-11-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observinglocation',
            name='artificial_brightness',
            field=models.FloatField(blank=True, help_text='µcd/m^2', null=True, verbose_name='Artif. Brightness'),
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_images/', verbose_name='Image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('direction', models.CharField(blank=True, choices=[('N', 'North'), ('NE', 'Northeast'), ('E', 'East'), ('SE', 'Southeast'), ('S', 'South'), ('SW', 'Southwest'), ('W', 'West'), ('NW', 'Northwest')], max_length=2, null=True, verbose_name='Direction')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation')),
            ],
        ),
    ]
