# Generated by Django 3.2.9 on 2021-11-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0002_auto_20211126_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='ratio',
            field=models.FloatField(blank=True, help_text='artificial to natural brightness', null=True, verbose_name='Ratio'),
        ),
    ]
