# Generated by Django 3.2.9 on 2021-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0003_observinglocation_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='bortle_image',
            field=models.ImageField(blank=True, null=True, upload_to='bortle_maps/', verbose_name='Bortle Map'),
        ),
        migrations.AddField(
            model_name='observinglocation',
            name='earth_image',
            field=models.ImageField(blank=True, null=True, upload_to='earth_maps/', verbose_name='Google Earth Image'),
        ),
        migrations.AddField(
            model_name='observinglocation',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='street_maps/', verbose_name='Google Map Image'),
        ),
    ]
