# Generated by Django 3.2.9 on 2021-11-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0004_auto_20211126_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='travel_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Travel Distance'),
        ),
        migrations.AddField(
            model_name='observinglocation',
            name='travel_time',
            field=models.FloatField(blank=True, help_text='minutes', null=True, verbose_name='Travel Time'),
        ),
        migrations.AlterField(
            model_name='observinglocation',
            name='state',
            field=models.CharField(choices=[('CT', 'CT'), ('MA', 'MA'), ('ME', 'ME'), ('NH', 'NH'), ('NY', 'NY')], default='MA', max_length=2, verbose_name='State'),
        ),
        migrations.DeleteModel(
            name='DistanceUser',
        ),
    ]
