# Generated by Django 3.2.9 on 2021-11-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0005_auto_20211127_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observinglocation',
            name='bortle',
            field=models.PositiveIntegerField(verbose_name='Bortle'),
        ),
        migrations.AlterField(
            model_name='observinglocation',
            name='travel_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Dist.'),
        ),
        migrations.AlterField(
            model_name='observinglocation',
            name='travel_time',
            field=models.FloatField(blank=True, help_text='minutes', null=True, verbose_name='Tr. Time'),
        ),
    ]
