# Generated by Django 3.2.9 on 2021-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0006_auto_20211127_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='status',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='TBD', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='observinglocation',
            name='state',
            field=models.CharField(choices=[('CT', 'CT'), ('MA', 'MA'), ('ME', 'ME'), ('NH', 'NH'), ('NY', 'NY'), ('VT', 'VT')], default='MA', max_length=2, verbose_name='State'),
        ),
    ]
