# Generated by Django 3.2.9 on 2021-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0007_auto_20211127_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observinglocation',
            name='status',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Possible', 'Possible'), ('Issues', 'Issues'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='TBD', max_length=50, verbose_name='Status'),
        ),
    ]
