# Generated by Django 4.0 on 2021-12-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0008_alter_observinglocation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observinglocation',
            options={'ordering': ['travel_distance']},
        ),
    ]
