# Generated by Django 4.0 on 2021-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0009_alter_observinglocation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observinglocation',
            name='status',
            field=models.CharField(choices=[('TBD', 'TBD'), ('Possible', 'Possible'), ('Issues', 'Issues'), ('Provisional', 'Provisional'), ('Active', 'Active'), ('Rejected', 'Rejected')], default='TBD', max_length=50, verbose_name='Status'),
        ),
    ]
