# Generated by Django 4.0 on 2021-12-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0010_alter_observinglocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='time_zone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('US/Eastern', 'US/Eastern')], default='UTC', max_length=20, verbose_name='Time Zone'),
        ),
    ]
