# Generated by Django 4.0 on 2021-12-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0011_observinglocation_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observinglocation',
            name='time_zone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('US/Eastern', 'US/Eastern')], default='US/Eastern', max_length=20, verbose_name='Time Zone'),
        ),
    ]
