# Generated by Django 4.0 on 2022-01-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0012_alter_observinglocation_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observinglocation',
            old_name='time_zone',
            new_name='x_time_zone',
        ),
    ]
