# Generated by Django 4.0 on 2022-01-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0014_observinglocation_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observinglocation',
            old_name='state',
            new_name='x_state',
        ),
        migrations.RemoveField(
            model_name='observinglocation',
            name='x_time_zone',
        ),
    ]
