# Generated by Django 4.0 on 2022-01-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_alter_stateregion_options_alter_timezone_options'),
        ('observe', '0015_rename_state_observinglocation_x_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misc.stateregion'),
            preserve_default=False,
        ),
    ]
