# Generated by Django 4.0 on 2022-01-03 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0016_observinglocation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observinglocation',
            name='x_state',
        ),
    ]
