# Generated by Django 4.2.19 on 2025-02-16 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0019_observinglocation_pdf_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservingLocationMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azimuth', models.FloatField(help_text='Inclusive - start at 0°', verbose_name='Azimuth')),
                ('altitude', models.FloatField(verbose_name='Altitude')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation')),
            ],
            options={
                'ordering': ['azimuth'],
            },
        ),
    ]
