# Generated by Django 4.2.19 on 2025-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0020_observinglocationmask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observinglocationmask',
            options={'ordering': ['azimuth_start']},
        ),
        migrations.RemoveField(
            model_name='observinglocationmask',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='observinglocationmask',
            name='azimuth',
        ),
        migrations.AddField(
            model_name='observinglocationmask',
            name='altitude_end',
            field=models.FloatField(default=0.0, verbose_name='Altitude End'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observinglocationmask',
            name='altitude_start',
            field=models.FloatField(default=0.0, verbose_name='Altitude Start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observinglocationmask',
            name='azimuth_end',
            field=models.FloatField(default=0.0, help_text='Exclusive', verbose_name='Azimuth End'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observinglocationmask',
            name='azimuth_start',
            field=models.FloatField(default=0.0, help_text='Inclusive - start at 0°', verbose_name='Azimuth Start'),
            preserve_default=False,
        ),
    ]
