# Generated by Django 4.2.19 on 2025-03-14 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_timezone_abbreviation'),
        ('observe', '0021_alter_observinglocationmask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region/Country'),
        ),
        migrations.AlterField(
            model_name='observinglocation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.stateregion'),
        ),
    ]
