# Generated by Django 4.2.19 on 2025-03-14 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0018_country'),
        ('observe', '0022_observinglocation_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observinglocation',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.stateregion'),
        ),
    ]
