# Generated by Django 4.2.19 on 2025-03-14 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0019_alter_country_options'),
        ('observe', '0023_alter_observinglocation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.country'),
        ),
    ]
