# Generated by Django 4.2.19 on 2025-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0024_observinglocation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Default Location'),
        ),
        migrations.AlterField(
            model_name='observinglocation',
            name='region',
            field=models.CharField(blank=True, help_text='For outside US/Canada', max_length=100, null=True, verbose_name='Region/Country'),
        ),
    ]
