# Generated by Django 4.2.27 on 2026-02-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0025_observinglocation_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observinglocation',
            name='azimuthal_map',
            field=models.ImageField(blank=True, null=True, upload_to='azimuthal_maps/', verbose_name='Azimuthal Map'),
        ),
        migrations.AddField(
            model_name='observinglocation',
            name='sqm_date',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
