# Generated by Django 4.2.9 on 2024-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso_observing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetobservingmode",
            name="viable",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Viable"),
                    (1, "Unlikely Viable"),
                    (2, "Extreme Difficulty"),
                    (3, "Very Difficult"),
                    (4, "Challenging"),
                    (5, "Requires Patience"),
                    (6, "Generally Visible"),
                    (7, "Usually Easy"),
                    (8, "Easy"),
                    (9, "Very Easy"),
                    (10, "Extremely easy"),
                ],
                verbose_name="Viability",
            ),
        ),
    ]
