# Generated by Django 4.2.9 on 2024-02-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso_observing", "0003_targetdso_ready_to_go"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="targetdso",
            options={"ordering": ["dso__constellation", "dso__shown_name"]},
        ),
        migrations.AlterField(
            model_name="targetobservingmode",
            name="viable",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Not Viable"),
                    (1, "Unlikely Viable"),
                    (2, "Extreme Difficulty"),
                    (3, "(Very) Difficult"),
                    (4, "Challenging"),
                    (5, "Requires Patience"),
                    (6, "Generally Visible"),
                    (7, "Usually Easy"),
                    (8, "Easy"),
                    (9, "Very Easy"),
                    (10, "Extremely easy"),
                ],
                verbose_name="Viability",
            ),
        ),
    ]
