# Generated by Django 4.2.9 on 2025-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dso_observing", "0004_alter_targetdso_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetobservingmode",
            name="priority",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Lowest"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Highest"),
                ],
                null=True,
            ),
        ),
    ]
