# Generated by Django 4.0 on 2021-12-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('load', models.CharField(blank=True, max_length=20, null=True, verbose_name='BSP File Name')),
                ('diameter', models.FloatField(help_text='Kilometers', verbose_name='Diameter')),
                ('moon_names', models.CharField(help_text='List of moons that might be observable; separate with commas', max_length=100, verbose_name='Moon Names')),
            ],
        ),
    ]
