# Generated by Django 4.0 on 2021-12-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='moon_names',
            field=models.CharField(blank=True, help_text='List of moons that might be observable; separate with commas', max_length=100, null=True, verbose_name='Moon Names'),
        ),
    ]
