# Generated by Django 4.0 on 2022-01-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0002_alter_planet_moon_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
