# Generated by Django 4.0.1 on 2022-01-05 01:54

from django.db import migrations, models
import djangoyearlessdate.models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0004_alter_planet_options_planet_semi_major_axis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorShower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('start_date', djangoyearlessdate.models.YearlessDateField(max_length=4, verbose_name='Start Date')),
                ('end_date', djangoyearlessdate.models.YearlessDateField(max_length=4, verbose_name='End Date')),
                ('peak_date', djangoyearlessdate.models.YearlessDateField(max_length=4, verbose_name='Peak Date')),
                ('radiant_ra', models.FloatField(verbose_name='Radiant RA')),
                ('radiant_dec', models.FloatField(verbose_name='Radiant Dec.')),
                ('longitude', models.FloatField(verbose_name='Celestial Longitude')),
                ('speed', models.PositiveIntegerField(blank=True, help_text='km/s', null=True, verbose_name='Avg. Speed')),
                ('zhr', models.PositiveIntegerField(blank=True, null=True, verbose_name='ZHR')),
                ('parent_body', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Body')),
            ],
        ),
    ]
