# Generated by Django 4.0.1 on 2022-01-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0005_meteorshower'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorshower',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
