# Generated by Django 4.0.1 on 2022-01-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0006_meteorshower_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='planet_map',
            field=models.ImageField(blank=True, null=True, upload_to='planet_maps', verbose_name='Planet Map'),
        ),
    ]
