# Generated by Django 4.0.1 on 2022-01-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0007_planet_planet_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.CharField(blank=True, help_text='Epoch of osculation of the orbital elements', max_length=5, null=True, verbose_name='MPC Epoch')),
                ('mean_anomaly', models.FloatField(verbose_name='Mean Anomaly')),
                ('arg_perihelion', models.FloatField(verbose_name='Arg. of Perihelion')),
                ('long_asc_node', models.FloatField(verbose_name='Long. of Asc. Node')),
                ('inclination', models.FloatField(verbose_name='Inclination')),
                ('eccentricity', models.FloatField(verbose_name='Eccentricity')),
                ('daily_motion', models.FloatField(verbose_name='Daily Motion')),
                ('semi_major_axis', models.FloatField(verbose_name='Semi-Major Axis')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('diameter', models.CharField(blank=True, help_text='# or # x # or # x # x #', max_length=50, null=True, verbose_name='Diameter')),
                ('year_of_discovery', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Discovery')),
                ('image', models.ImageField(blank=True, null=True, upload_to='asteroid_images', verbose_name='Image')),
                ('classification', models.CharField(blank=True, max_length=10, null=True, verbose_name='Classification')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('h', models.FloatField(help_text='absolute magnitude', verbose_name='H')),
                ('g', models.FloatField(help_text='slope parameter', verbose_name='G')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
