# Generated by Django 4.0.1 on 2022-01-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0009_alter_asteroid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='slug',
            field=models.SlugField(default='foo', verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
