# Generated by Django 4.0.1 on 2022-01-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0010_asteroid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='est_brightest',
            field=models.FloatField(blank=True, null=True, verbose_name='Estimated Brightest'),
        ),
    ]
