# Generated by Django 4.0.1 on 2022-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0011_asteroid_est_brightest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('status', models.PositiveIntegerField(choices=[(1, 'On'), (0, 'Off')], default=1, verbose_name='Status')),
            ],
        ),
    ]
