# Generated by Django 4.0.1 on 2022-02-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_eyepiece_telescope'),
        ('solar_system', '0013_planetobservation_cometobservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidobservation',
            name='eyepieces',
            field=models.ManyToManyField(to='tech.Eyepiece'),
        ),
        migrations.AddField(
            model_name='asteroidobservation',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, choices=[(5, 'Excellent: stable diffraction rings'), (4, 'Good: light undulations across diffraction rings'), (3, 'Fair: broken diffraction rings; central disk deformations'), (2, 'Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, 'Fail: boiling image; no sign of diffraction pattern')], null=True, verbose_name='Seeing'),
        ),
        migrations.AddField(
            model_name='asteroidobservation',
            name='sqm',
            field=models.FloatField(blank=True, null=True, verbose_name='SQM'),
        ),
        migrations.AddField(
            model_name='asteroidobservation',
            name='telescope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.telescope'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='eyepieces',
            field=models.ManyToManyField(to='tech.Eyepiece'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, choices=[(5, 'Excellent: stable diffraction rings'), (4, 'Good: light undulations across diffraction rings'), (3, 'Fair: broken diffraction rings; central disk deformations'), (2, 'Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, 'Fail: boiling image; no sign of diffraction pattern')], null=True, verbose_name='Seeing'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='sqm',
            field=models.FloatField(blank=True, null=True, verbose_name='SQM'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='telescope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.telescope'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='eyepieces',
            field=models.ManyToManyField(to='tech.Eyepiece'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, choices=[(5, 'Excellent: stable diffraction rings'), (4, 'Good: light undulations across diffraction rings'), (3, 'Fair: broken diffraction rings; central disk deformations'), (2, 'Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, 'Fail: boiling image; no sign of diffraction pattern')], null=True, verbose_name='Seeing'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='sqm',
            field=models.FloatField(blank=True, null=True, verbose_name='SQM'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='telescope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.telescope'),
        ),
    ]
