# Generated by Django 4.0.1 on 2022-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0014_asteroidobservation_eyepieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidobservation',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5 = Excellent: stable diffraction rings'), (4, '4 = Good: light undulations across diffraction rings'), (3, '3 = Fair: broken diffraction rings; central disk deformations'), (2, '2 = Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, '1 = Fail: boiling image; no sign of diffraction pattern')], null=True, verbose_name='Seeing'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5 = Excellent: stable diffraction rings'), (4, '4 = Good: light undulations across diffraction rings'), (3, '3 = Fair: broken diffraction rings; central disk deformations'), (2, '2 = Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, '1 = Fail: boiling image; no sign of diffraction pattern')], null=True, verbose_name='Seeing'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='seeing',
            field=models.PositiveIntegerField(blank=True, choices=[(5, '5 = Excellent: stable diffraction rings'), (4, '4 = Good: light undulations across diffraction rings'), (3, '3 = Fair: broken diffraction rings; central disk deformations'), (2, '2 = Poor: (partly) missing diffraction rings; eddy streams in central disk'), (1, '1 = Fail: boiling image; no sign of diffraction pattern')], null=True, verbose_name='Seeing'),
        ),
    ]
