# Generated by Django 4.0.2 on 2022-02-09 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0018_remove_asteroidobservation_ut_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 18, 41, 696079), help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 18, 46, 727813), help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 18, 18, 52, 39858), help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
            preserve_default=False,
        ),
    ]
