# Generated by Django 4.0.2 on 2022-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0019_asteroidobservation_ut_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidobservation',
            name='ut_date',
        ),
        migrations.RemoveField(
            model_name='asteroidobservation',
            name='ut_time',
        ),
        migrations.RemoveField(
            model_name='cometobservation',
            name='ut_date',
        ),
        migrations.RemoveField(
            model_name='cometobservation',
            name='ut_time',
        ),
        migrations.RemoveField(
            model_name='planetobservation',
            name='ut_date',
        ),
        migrations.RemoveField(
            model_name='planetobservation',
            name='ut_time',
        ),
    ]
