# Generated by Django 4.0.2 on 2022-02-09 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0020_remove_asteroidobservation_ut_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime.utcnow, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime.utcnow, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=datetime.datetime.utcnow, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
    ]
