# Generated by Django 4.0.2 on 2022-02-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0017_remove_observinglocation_x_state'),
        ('solar_system', '0021_alter_asteroidobservation_ut_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidobservation',
            name='location',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='location',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='location',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
