# Generated by Django 4.0.2 on 2022-02-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0017_remove_observinglocation_x_state'),
        ('solar_system', '0022_asteroidobservation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidobservation',
            name='location',
            field=models.ForeignKey(default=43, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='location',
            field=models.ForeignKey(default=43, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='location',
            field=models.ForeignKey(default=43, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
