# Generated by Django 4.0.2 on 2022-02-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_eyepiece_short_name_filter_short_name'),
        ('solar_system', '0023_alter_asteroidobservation_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidobservation',
            name='filters',
            field=models.ManyToManyField(to='tech.Filter'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='filters',
            field=models.ManyToManyField(to='tech.Filter'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='filters',
            field=models.ManyToManyField(to='tech.Filter'),
        ),
    ]
