# Generated by Django 4.0.4 on 2022-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_eyepiece_short_name_filter_short_name'),
        ('solar_system', '0024_asteroidobservation_filters_cometobservation_filters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidobservation',
            name='eyepieces',
            field=models.ManyToManyField(blank=True, to='tech.eyepiece'),
        ),
        migrations.AlterField(
            model_name='asteroidobservation',
            name='filters',
            field=models.ManyToManyField(blank=-1, to='tech.filter'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='eyepieces',
            field=models.ManyToManyField(blank=True, to='tech.eyepiece'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='filters',
            field=models.ManyToManyField(blank=-1, to='tech.filter'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='eyepieces',
            field=models.ManyToManyField(blank=True, to='tech.eyepiece'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='filters',
            field=models.ManyToManyField(blank=-1, to='tech.filter'),
        ),
    ]
