# Generated by Django 4.0.4 on 2022-04-28 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0013_eyepiece_short_name_filter_short_name'),
        ('observe', '0019_observinglocation_pdf_form'),
        ('solar_system', '0025_alter_asteroidobservation_eyepieces_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ut_datetime', models.DateTimeField(default=datetime.datetime.utcnow, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('eyepieces', models.ManyToManyField(blank=True, to='tech.eyepiece')),
                ('filters', models.ManyToManyField(blank=-1, to='tech.filter')),
                ('location', models.ForeignKey(default=43, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation')),
                ('telescope', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tech.telescope')),
            ],
            options={
                'verbose_name': 'Observation',
                'verbose_name_plural': 'Observations',
            },
        ),
    ]
