# Generated by Django 4.0.4 on 2022-04-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0026_moonobservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moonobservation',
            options={'verbose_name': 'Moon Observation', 'verbose_name_plural': 'Moon Observations'},
        ),
    ]
