# Generated by Django 4.0.4 on 2022-06-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0019_observinglocation_pdf_form'),
        ('solar_system', '0027_alter_moonobservation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidobservation',
            name='location',
            field=models.ForeignKey(default=48, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='location',
            field=models.ForeignKey(default=48, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='moonobservation',
            name='location',
            field=models.ForeignKey(default=48, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='location',
            field=models.ForeignKey(default=48, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
