# Generated by Django 4.0.4 on 2022-08-28 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0029_comet_mag_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetMoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('planet_index', models.PositiveIntegerField(verbose_name='Index')),
                ('radius', models.FloatField(help_text='km', verbose_name='Radius')),
                ('h', models.FloatField(help_text='abs. mag', verbose_name='H')),
                ('g', models.FloatField(default=0.15, help_text='slope parameter', verbose_name='G')),
                ('period', models.FloatField(help_text='hours', verbose_name='Period')),
                ('use_in_modeling', models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_system.planet')),
            ],
        ),
    ]
