# Generated by Django 4.0.4 on 2022-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0030_planetmoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetmoon',
            name='albedo',
            field=models.FloatField(default=0.0, verbose_name='Albedo'),
            preserve_default=False,
        ),
    ]
