# Generated by Django 4.0.4 on 2022-08-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0031_planetmoon_albedo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planetmoon',
            options={'verbose_name': 'Planetary Satellite', 'verbose_name_plural': 'Planetary Satellites'},
        ),
        migrations.AddField(
            model_name='planetmoon',
            name='major_axis',
            field=models.FloatField(blank=True, help_text='km', null=True, verbose_name='Dist. from Planet'),
        ),
    ]
