# Generated by Django 4.0.4 on 2022-10-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0016_alter_observingcircumstances_session_stage'),
        ('solar_system', '0032_alter_planetmoon_options_planetmoon_major_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidobservation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.observingsession'),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.observingsession'),
        ),
        migrations.AddField(
            model_name='moonobservation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.observingsession'),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.observingsession'),
        ),
    ]
