# Generated by Django 4.0.4 on 2022-12-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0034_meteorshower_intenside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteorshower',
            old_name='intenside',
            new_name='intensity',
        ),
    ]
