# Generated by Django 4.0.4 on 2023-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0035_rename_intenside_meteorshower_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comet',
            name='light_curve_url',
            field=models.URLField(blank=True, null=True, verbose_name='Light Curve URL'),
        ),
    ]
