# Generated by Django 4.0.4 on 2023-07-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0036_comet_light_curve_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidobservation',
            name='imaging_status',
            field=models.IntegerField(choices=[(0, 'No Images'), (1, 'Image Taken'), (2, 'Multiple Images Taken')], default=0),
        ),
        migrations.AddField(
            model_name='cometobservation',
            name='imaging_status',
            field=models.IntegerField(choices=[(0, 'No Images'), (1, 'Image Taken'), (2, 'Multiple Images Taken')], default=0),
        ),
        migrations.AddField(
            model_name='moonobservation',
            name='imaging_status',
            field=models.IntegerField(choices=[(0, 'No Images'), (1, 'Image Taken'), (2, 'Multiple Images Taken')], default=0),
        ),
        migrations.AddField(
            model_name='planetobservation',
            name='imaging_status',
            field=models.IntegerField(choices=[(0, 'No Images'), (1, 'Image Taken'), (2, 'Multiple Images Taken')], default=0),
        ),
    ]
