# Generated by Django 4.0.4 on 2023-07-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0038_asteroidobservation_num_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comet',
            name='override_limits',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
