# Generated by Django 4.0.4 on 2023-08-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0041_cometibraryimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CometibraryImage',
            new_name='CometLibraryImage',
        ),
    ]
