# Generated by Django 4.0.4 on 2023-08-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0043_alter_cometlibraryimage_options_planetlibraryimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planetlibraryimage',
            options={'verbose_name': 'Planet Library Images'},
        ),
    ]
