# Generated by Django 4.0.4 on 2023-08-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0044_alter_planetlibraryimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='always_include',
            field=models.BooleanField(default=False, help_text='Override magnitude limit, e.g., for Pluto', verbose_name='Always Include'),
        ),
    ]
