# Generated by Django 4.0.4 on 2023-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0045_asteroid_always_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='comet',
            name='light_curve_graph_url',
            field=models.URLField(blank=True, null=True, verbose_name='Light Curve Graph URL'),
        ),
    ]
