# Generated by Django 4.0.4 on 2023-09-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0019_observinglocation_pdf_form'),
        ('solar_system', '0046_comet_light_curve_graph_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidlibraryimage',
            name='amateur_image',
        ),
        migrations.RemoveField(
            model_name='asteroidlibraryimage',
            name='own_image',
        ),
        migrations.RemoveField(
            model_name='cometlibraryimage',
            name='amateur_image',
        ),
        migrations.RemoveField(
            model_name='cometlibraryimage',
            name='own_image',
        ),
        migrations.RemoveField(
            model_name='planetlibraryimage',
            name='amateur_image',
        ),
        migrations.RemoveField(
            model_name='planetlibraryimage',
            name='own_image',
        ),
        migrations.AlterField(
            model_name='asteroidobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='moonobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
