# Generated by Django 4.0.4 on 2023-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0048_asteroidlibraryimage_image_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidlibraryimage',
            name='image_alterations',
            field=models.CharField(blank=True, choices=[('None', 'Raw'), ('annotated', 'Annotated'), ('processed', 'Processed')], default='None', max_length=30, null=True, verbose_name='Image Alterations'),
        ),
        migrations.AddField(
            model_name='cometlibraryimage',
            name='image_alterations',
            field=models.CharField(blank=True, choices=[('None', 'Raw'), ('annotated', 'Annotated'), ('processed', 'Processed')], default='None', max_length=30, null=True, verbose_name='Image Alterations'),
        ),
        migrations.AddField(
            model_name='planetlibraryimage',
            name='image_alterations',
            field=models.CharField(blank=True, choices=[('None', 'Raw'), ('annotated', 'Annotated'), ('processed', 'Processed')], default='None', max_length=30, null=True, verbose_name='Image Alterations'),
        ),
    ]
