# Generated by Django 4.2.9 on 2024-01-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_system", "0050_asteroidlibraryimage_use_in_carousel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidlibraryimage",
            name="use_in_carousel",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=1,
                help_text="Set to YES/1 show on the image carousel",
                verbose_name="Use in Slideshow",
            ),
        ),
        migrations.AlterField(
            model_name="cometlibraryimage",
            name="use_in_carousel",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=1,
                help_text="Set to YES/1 show on the image carousel",
                verbose_name="Use in Slideshow",
            ),
        ),
        migrations.AlterField(
            model_name="planetlibraryimage",
            name="use_in_carousel",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=1,
                help_text="Set to YES/1 show on the image carousel",
                verbose_name="Use in Slideshow",
            ),
        ),
    ]
