# Generated by Django 4.2.9 on 2024-05-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_system", "0051_alter_asteroidlibraryimage_use_in_carousel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidlibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
        migrations.AlterField(
            model_name="asteroidlibraryimage",
            name="processing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "Not Yet Started"),
                    ("Default", "Default Unistellar/Seestar Image"),
                    ("3-Step", "3-Step: Dark, Stretched, Cleaned"),
                    ("Pix+RCA", "Pixinsight + RC Astro"),
                    ("DB", "Processed image added to DB"),
                    ("Rejected", "Image Rejected"),
                    ("Unknown", "Unknown"),
                ],
                max_length=30,
                null=True,
                verbose_name="Image Processing Status",
            ),
        ),
        migrations.AlterField(
            model_name="cometlibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
        migrations.AlterField(
            model_name="cometlibraryimage",
            name="processing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "Not Yet Started"),
                    ("Default", "Default Unistellar/Seestar Image"),
                    ("3-Step", "3-Step: Dark, Stretched, Cleaned"),
                    ("Pix+RCA", "Pixinsight + RC Astro"),
                    ("DB", "Processed image added to DB"),
                    ("Rejected", "Image Rejected"),
                    ("Unknown", "Unknown"),
                ],
                max_length=30,
                null=True,
                verbose_name="Image Processing Status",
            ),
        ),
        migrations.AlterField(
            model_name="planetlibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
        migrations.AlterField(
            model_name="planetlibraryimage",
            name="processing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "Not Yet Started"),
                    ("Default", "Default Unistellar/Seestar Image"),
                    ("3-Step", "3-Step: Dark, Stretched, Cleaned"),
                    ("Pix+RCA", "Pixinsight + RC Astro"),
                    ("DB", "Processed image added to DB"),
                    ("Rejected", "Image Rejected"),
                    ("Unknown", "Unknown"),
                ],
                max_length=30,
                null=True,
                verbose_name="Image Processing Status",
            ),
        ),
    ]
