# Generated by Django 4.2.9 on 2024-06-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_system", "0053_asteroidlibraryimage_image_style_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asteroidlibraryimage",
            name="use_as_map",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                help_text="Set to YES/1 show on the map panel",
                verbose_name="Use in Map Panel",
            ),
        ),
        migrations.AddField(
            model_name="cometlibraryimage",
            name="use_as_map",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                help_text="Set to YES/1 show on the map panel",
                verbose_name="Use in Map Panel",
            ),
        ),
        migrations.AddField(
            model_name="planetlibraryimage",
            name="use_as_map",
            field=models.PositiveIntegerField(
                choices=[(1, "Yes"), (0, "No")],
                default=0,
                help_text="Set to YES/1 show on the map panel",
                verbose_name="Use in Map Panel",
            ),
        ),
    ]
