# Generated by Django 4.2.9 on 2024-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_system", "0054_asteroidlibraryimage_use_as_map_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asteroidlibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                    ("s-crop", "Seestar S50: Cropped"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
        migrations.AlterField(
            model_name="cometlibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                    ("s-crop", "Seestar S50: Cropped"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
        migrations.AlterField(
            model_name="planetlibraryimage",
            name="image_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("e-crop", "eQuinox 2: Cropped"),
                    ("e-full", "eQuinox 2: Full"),
                    ("s-full", "Seestar S50: Full"),
                    ("s-crop", "Seestar S50: Cropped"),
                ],
                default=None,
                max_length=30,
                null=True,
                verbose_name="Image Type",
            ),
        ),
    ]
