# Generated by Django 4.2.9 on 2025-01-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_system", "0055_alter_asteroidlibraryimage_image_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comet",
            name="perihelion_date",
            field=models.DateField(blank=True, null=True, verbose_name="Peri."),
        ),
    ]
