# Generated by Django 4.2.19 on 2025-02-09 17:36

from django.db import migrations, models
import skytour.apps.astro.time


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0056_comet_perihelion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comet',
            options={'ordering': ['perihelion_date']},
        ),
        migrations.AlterField(
            model_name='asteroidobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=skytour.apps.astro.time.utc_now, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=skytour.apps.astro.time.utc_now, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
        migrations.AlterField(
            model_name='moonobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=skytour.apps.astro.time.utc_now, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='ut_datetime',
            field=models.DateTimeField(default=skytour.apps.astro.time.utc_now, help_text='Date/Time (UT)', verbose_name='UTDT of Obs.'),
        ),
    ]
