# Generated by Django 4.2.19 on 2025-02-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0058_alter_asteroidlibraryimage_exposure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidobservation',
            name='imaging_status',
        ),
        migrations.RemoveField(
            model_name='asteroidobservation',
            name='num_images',
        ),
        migrations.RemoveField(
            model_name='cometobservation',
            name='imaging_status',
        ),
        migrations.RemoveField(
            model_name='cometobservation',
            name='num_images',
        ),
        migrations.RemoveField(
            model_name='moonobservation',
            name='imaging_status',
        ),
        migrations.RemoveField(
            model_name='moonobservation',
            name='num_images',
        ),
        migrations.RemoveField(
            model_name='planetobservation',
            name='imaging_status',
        ),
        migrations.RemoveField(
            model_name='planetobservation',
            name='num_images',
        ),
    ]
