# Generated by Django 4.2.19 on 2025-02-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0059_remove_asteroidobservation_imaging_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidlibraryimage',
            name='image_style',
            field=models.CharField(blank=True, choices=[('square', 'Square/Library Image Carousel'), ('map', 'Annotated Image/Full Frame Carousel'), ('full', 'Full Frame Image/Full Frame Carousel'), ('other', 'Other')], max_length=30, null=True, verbose_name='Image Class'),
        ),
        migrations.AlterField(
            model_name='cometlibraryimage',
            name='image_style',
            field=models.CharField(blank=True, choices=[('square', 'Square/Library Image Carousel'), ('map', 'Annotated Image/Full Frame Carousel'), ('full', 'Full Frame Image/Full Frame Carousel'), ('other', 'Other')], max_length=30, null=True, verbose_name='Image Class'),
        ),
        migrations.AlterField(
            model_name='planetlibraryimage',
            name='image_style',
            field=models.CharField(blank=True, choices=[('square', 'Square/Library Image Carousel'), ('map', 'Annotated Image/Full Frame Carousel'), ('full', 'Full Frame Image/Full Frame Carousel'), ('other', 'Other')], max_length=30, null=True, verbose_name='Image Class'),
        ),
    ]
