# Generated by Django 4.2.19 on 2025-03-09 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0020_alter_telescope_active'),
        ('solar_system', '0060_alter_asteroidlibraryimage_image_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidlibraryimage',
            name='image_cropping',
            field=models.CharField(blank=True, choices=[('full', 'Full-Size'), ('cropped', 'Cropped')], max_length=20, null=True, verbose_name='Image Cropping'),
        ),
        migrations.AddField(
            model_name='asteroidlibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('landscape', 'Landscape'), ('portrait', 'Portait')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
        migrations.AddField(
            model_name='asteroidlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('unknnown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AddField(
            model_name='asteroidlibraryimage',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tech.telescope'),
        ),
        migrations.AddField(
            model_name='cometlibraryimage',
            name='image_cropping',
            field=models.CharField(blank=True, choices=[('full', 'Full-Size'), ('cropped', 'Cropped')], max_length=20, null=True, verbose_name='Image Cropping'),
        ),
        migrations.AddField(
            model_name='cometlibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('landscape', 'Landscape'), ('portrait', 'Portait')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
        migrations.AddField(
            model_name='cometlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('unknnown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AddField(
            model_name='cometlibraryimage',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tech.telescope'),
        ),
        migrations.AddField(
            model_name='planetlibraryimage',
            name='image_cropping',
            field=models.CharField(blank=True, choices=[('full', 'Full-Size'), ('cropped', 'Cropped')], max_length=20, null=True, verbose_name='Image Cropping'),
        ),
        migrations.AddField(
            model_name='planetlibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('landscape', 'Landscape'), ('portrait', 'Portait')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
        migrations.AddField(
            model_name='planetlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('unknnown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AddField(
            model_name='planetlibraryimage',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tech.telescope'),
        ),
    ]
