# Generated by Django 4.2.19 on 2025-03-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0062_alter_asteroidlibraryimage_image_orientation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidlibraryimage',
            name='image_alterations',
        ),
        migrations.RemoveField(
            model_name='asteroidlibraryimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='asteroidlibraryimage',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='cometlibraryimage',
            name='image_alterations',
        ),
        migrations.RemoveField(
            model_name='cometlibraryimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='cometlibraryimage',
            name='processing_status',
        ),
        migrations.RemoveField(
            model_name='planetlibraryimage',
            name='image_alterations',
        ),
        migrations.RemoveField(
            model_name='planetlibraryimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='planetlibraryimage',
            name='processing_status',
        ),
        migrations.AlterField(
            model_name='asteroidlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AlterField(
            model_name='cometlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AlterField(
            model_name='planetlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
    ]
