# Generated by Django 4.2.19 on 2025-03-14 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0063_remove_asteroidlibraryimage_image_alterations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroidlibraryimage',
            name='image_style',
        ),
        migrations.RemoveField(
            model_name='cometlibraryimage',
            name='image_style',
        ),
        migrations.RemoveField(
            model_name='planetlibraryimage',
            name='image_style',
        ),
    ]
