# Generated by Django 4.2.19 on 2025-03-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0065_alter_asteroidobservation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('annotated', 'Annotated'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AlterField(
            model_name='cometlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('annotated', 'Annotated'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
        migrations.AlterField(
            model_name='planetlibraryimage',
            name='image_processing_status',
            field=models.CharField(blank=True, choices=[('default', 'Default'), ('post-processed', 'Post Processed'), ('annotated', 'Annotated'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='Image Processing Status'),
        ),
    ]
