# Generated by Django 4.2.19 on 2025-04-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0066_alter_asteroidlibraryimage_image_processing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comet',
            name='light_curve_graph_url',
            field=models.URLField(blank=True, help_text='URL for the light curve at http://www.aerith.net', null=True, verbose_name='Light Curve Graph URL'),
        ),
        migrations.AlterField(
            model_name='comet',
            name='light_curve_url',
            field=models.URLField(blank=True, help_text='Comet page at http://www.aerith.net', null=True, verbose_name='Light Curve URL'),
        ),
        migrations.AlterField(
            model_name='comet',
            name='mag_offset',
            field=models.FloatField(default=0.0, help_text='Offset Mag if esp. brighter/dimmer than predicted', verbose_name='Mag Offset'),
        ),
        migrations.AlterField(
            model_name='comet',
            name='name',
            field=models.CharField(help_text='MPC format, e.g. 1P/Halley, C/2025 F2', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comet',
            name='override_limits',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, help_text='Force adding to cookie, regardless of magnitude'),
        ),
        migrations.AlterField(
            model_name='comet',
            name='perihelion_date',
            field=models.DateField(blank=True, help_text='Auto calcualted from elements', null=True, verbose_name='Peri.'),
        ),
        migrations.AlterField(
            model_name='comet',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'On'), (0, 'Off')], default=1, help_text='Include in Cookie', verbose_name='Status'),
        ),
    ]
