# Generated by Django 4.2.19 on 2025-04-10 20:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0067_alter_comet_light_curve_graph_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroid',
            name='mpc_json',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON object constructed from HyperLeda lookup', null=True, verbose_name='MPC as JSON'),
        ),
    ]
