# Generated by Django 4.2.19 on 2025-04-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0068_asteroid_mpc_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asteroid',
            name='g',
        ),
        migrations.RemoveField(
            model_name='asteroid',
            name='h',
        ),
    ]
