# Generated by Django 4.2.23 on 2025-06-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0069_remove_asteroid_g_remove_asteroid_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidlibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('mosaic', 'Mosaic'), ('landscape', 'Landscape'), ('portrait', 'Portait'), ('other', 'Other')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
        migrations.AlterField(
            model_name='cometlibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('mosaic', 'Mosaic'), ('landscape', 'Landscape'), ('portrait', 'Portait'), ('other', 'Other')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
        migrations.AlterField(
            model_name='planetlibraryimage',
            name='image_orientation',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('mosaic', 'Mosaic'), ('landscape', 'Landscape'), ('portrait', 'Portait'), ('other', 'Other')], max_length=20, null=True, verbose_name='Image Orientation'),
        ),
    ]
