# Generated by Django 4.2.23 on 2025-06-23 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0070_alter_asteroidlibraryimage_image_orientation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_system.planet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeteorShowerWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_system.meteorshower')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CometWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_system.comet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsteroidWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_lookup', models.CharField(blank=True, help_text='Use to handle disambiguation', max_length=100, null=True, verbose_name='Override Lookup Text')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wikipedia Title')),
                ('exists', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; false if no page exists', null=True, verbose_name='Exists')),
                ('ambiguous', models.PositiveIntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], help_text='null if not looked up; true if lookup points to a disambiguation page - need to rerun w/ override text!', null=True, verbose_name='Is Ambiguous')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('summary_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Summary Length')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Canonical URL')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar_system.asteroid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
