# Generated by Django 4.2.23 on 2025-06-23 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0071_planetwiki_meteorshowerwiki_cometwiki_asteroidwiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidwiki',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar_system.asteroid'),
        ),
        migrations.AlterField(
            model_name='cometwiki',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar_system.comet'),
        ),
        migrations.AlterField(
            model_name='meteorshowerwiki',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar_system.meteorshower'),
        ),
        migrations.AlterField(
            model_name='planetwiki',
            name='object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar_system.planet'),
        ),
    ]
