# Generated by Django 4.2.23 on 2025-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0073_remove_asteroidwiki_id_remove_cometwiki_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorshower',
            name='radiant_map',
            field=models.ImageField(blank=True, null=True, upload_to='meteor_map', verbose_name='Radiant Map'),
        ),
    ]
