# Generated by Django 4.2.25 on 2025-10-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_system', '0074_meteorshower_radiant_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteorshower',
            options={'ordering': ['peak_date']},
        ),
    ]
