# Generated by Django 4.2.25 on 2025-12-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0025_observinglocation_is_default_and_more'),
        ('solar_system', '0075_alter_meteorshower_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asteroidobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='cometobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='moonobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
        migrations.AlterField(
            model_name='planetobservation',
            name='location',
            field=models.ForeignKey(default=1, limit_choices_to={'status__in': ['Active', 'Provisional']}, on_delete=django.db.models.deletion.CASCADE, to='observe.observinglocation'),
        ),
    ]
