# Generated by Django 4.0 on 2022-01-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateregion',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='timezone',
            options={'ordering': ['utc_offset']},
        ),
    ]
