# Generated by Django 4.0 on 2022-01-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_rename_type_calendar_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='icon',
            field=models.CharField(default='x', max_length=10, verbose_name='Icon'),
        ),
    ]
