# Generated by Django 4.0 on 2022-01-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_eventtype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(blank=True, choices=[('Planet', 'Planet'), ('DSO', 'DSO')], max_length=40, null=True, verbose_name='Reference Model')),
                ('reference', models.CharField(help_text='e.g., Jupiter, Io, NGC 7654, Moon, Sun', max_length=100, verbose_name='Reference')),
            ],
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Calendar Entry', 'verbose_name_plural': 'Calendar Items'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='involves',
            field=models.ManyToManyField(to='misc.CalendarEventReference'),
        ),
    ]
