# Generated by Django 4.0 on 2022-01-04 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_calendareventreference_alter_calendar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendareventreference',
            name='calendar_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='misc.calendar'),
            preserve_default=False,
        ),
    ]
