# Generated by Django 4.0.1 on 2022-01-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_calendareventreference_calendar_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['slug']},
        ),
    ]
