# Generated by Django 4.0.1 on 2022-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateregion',
            name='marker',
            field=models.CharField(default='o', max_length=5, verbose_name='Marker for Plot'),
        ),
    ]
