# Generated by Django 4.0.2 on 2022-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_stateregion_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateregion',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Abbreviation'),
        ),
    ]
