# Generated by Django 4.0.2 on 2022-02-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0010_stateregion_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name/Topic')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('link', models.URLField(blank=True, help_text='External link for more information', null=True, verbose_name='Link')),
            ],
        ),
    ]
