# Generated by Django 4.0.2 on 2022-02-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0011_glossary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossary',
            options={'ordering': ['slug'], 'verbose_name': 'Glossary Entry', 'verbose_name_plural': 'Glossary Entries'},
        ),
    ]
