# Generated by Django 4.0.4 on 2022-12-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_alter_glossary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendareventreference',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('Planet', 'Planet'), ('DSO', 'DSO'), ('Asteroid', 'Asteroid'), ('Moon', 'Moon'), ('Sun', 'Sun'), ('Comet', 'Comet')], max_length=40, null=True, verbose_name='Reference Model'),
        ),
    ]
