# Generated by Django 4.2.9 on 2024-11-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0013_alter_calendareventreference_reference_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendareventreference",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Planet", "Planet"),
                    ("DSO", "DSO"),
                    ("Asteroid", "Asteroid"),
                    ("Moon", "Moon"),
                    ("Sun", "Sun"),
                    ("Comet", "Comet"),
                    ("Star", "Star"),
                ],
                max_length=40,
                null=True,
                verbose_name="Reference Model",
            ),
        ),
    ]
