# Generated by Django 4.2.19 on 2025-03-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0014_alter_calendareventreference_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('pdf_file', models.FileField(upload_to='pdf_files', verbose_name='PDF File')),
            ],
        ),
    ]
