# Generated by Django 4.2.19 on 2025-03-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0015_pdfmanual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfmanual',
            options={'ordering': ['slug']},
        ),
    ]
