# Generated by Django 4.2.19 on 2025-03-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0016_alter_pdfmanual_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='abbreviation',
            field=models.CharField(default='', max_length=5, verbose_name='Abbreviation'),
            preserve_default=False,
        ),
    ]
