# Generated by Django 4.2.19 on 2025-03-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0017_timezone_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name ')),
                ('code', models.CharField(max_length=2, verbose_name='Code')),
            ],
        ),
    ]
