# Generated by Django 4.2.19 on 2025-03-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0018_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
