# Generated by Django 4.2.19 on 2025-03-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0019_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateregion',
            options={'ordering': ['pk']},
        ),
    ]
