# Generated by Django 4.2.19 on 2025-03-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0020_alter_stateregion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='pytz_label',
            field=models.CharField(blank=True, help_text='Needed for local time, help with DST', max_length=50, null=True, verbose_name='PYTZ Label'),
        ),
    ]
