# Generated by Django 4.2.19 on 2025-04-02 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0021_timezone_pytz_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(blank=True, choices=[('Planet', 'Planet'), ('DSO', 'DSO'), ('Asteroid', 'Asteroid'), ('Moon', 'Moon'), ('Sun', 'Sun'), ('Comet', 'Comet'), ('Star', 'Star')], max_length=40, null=True, verbose_name='Reference Model')),
                ('reference', models.CharField(help_text='e.g., Jupiter, Io, NGC 7654, Moon, Sun', max_length=100, verbose_name='Reference')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.calendar')),
            ],
        ),
    ]
