# Generated by Django 4.2.19 on 2025-04-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0022_calendarentryreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='involves',
        ),
        migrations.DeleteModel(
            name='CalendarEntryReference',
        ),
    ]
