# Generated by Django 4.2.25 on 2025-10-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0023_remove_calendar_involves_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='calendareventreference',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('Planet', 'Planet'), ('DSO', 'DSO'), ('Asteroid', 'Asteroid'), ('Moon', 'Moon'), ('Sun', 'Sun'), ('Comet', 'Comet'), ('Star', 'Star'), ('Meteor Shower', 'MeteorShower')], max_length=40, null=True, verbose_name='Reference Model'),
        ),
    ]
