# Generated by Django 4.2.27 on 2026-02-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0024_alter_eventtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='table_html',
            field=models.TextField(blank=True, help_text='Optional table in HTML.', null=True, verbose_name='Optional Table (HTML)'),
        ),
        migrations.AlterField(
            model_name='glossary',
            name='description',
            field=models.TextField(default='', help_text='Main content, allows HTML formatting.', verbose_name='HTML Content'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='GlossaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='glossary_images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption')),
                ('order_by', models.PositiveIntegerField(default=0, verbose_name='Order By')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='misc.glossary')),
            ],
        ),
    ]
