# Generated by Django 4.0.1 on 2022-01-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParameterFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('value', models.FloatField(default=0.0, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteParameterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('value', models.ImageField(upload_to='', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteParameterPositiveInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteParamterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('value', models.URLField(verbose_name='URL')),
                ('link_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Link Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteParamterNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('value', models.IntegerField(default=0, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteParamterString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('value', models.CharField(default='', max_length=200, verbose_name='Value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
