# Generated by Django 4.0.1 on 2022-01-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parameter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteParamterLink',
            new_name='SiteParameterLink',
        ),
        migrations.RenameModel(
            old_name='SiteParamterNumber',
            new_name='SiteParameterNumber',
        ),
        migrations.RenameModel(
            old_name='SiteParamterString',
            new_name='SiteParameterString',
        ),
    ]
