# Generated by Django 4.0.4 on 2022-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_parameter', '0004_siteparameterfloat_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParameterPDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('pdf', models.FileField(upload_to='pdf_files', verbose_name='PDF File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
