# Generated by Django 4.0.4 on 2022-04-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parameter', '0005_siteparameterpdffile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteparameterpdffile',
            old_name='pdf',
            new_name='value',
        ),
    ]
