# Generated by Django 4.2.19 on 2025-02-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_parameter', '0006_rename_pdf_siteparameterpdffile_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteparameterfloat',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='siteparameterimage',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='siteparameterlink',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='siteparameternumber',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='siteparameterpdffile',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='siteparameterpositiveinteger',
            options={'ordering': ['slug']},
        ),
        migrations.AlterModelOptions(
            name='siteparameterstring',
            options={'ordering': ['slug']},
        ),
    ]
