# Generated by Django 4.0.4 on 2023-12-30 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsteroidOccultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name='Obs. Date')),
                ('start_ut', models.TimeField(verbose_name='UT Start')),
                ('duration', models.FloatField(help_text='minutes', verbose_name='Obs. Duration')),
            ],
        ),
        migrations.CreateModel(
            name='OccultedStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_h', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(23)], verbose_name='RA: hr')),
                ('ra_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('ra_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('ra', models.FloatField(blank=True, null=True, verbose_name='R.A.')),
                ('ra_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='R.A. Text')),
                ('dec_sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='Dec: Sign')),
                ('dec_d', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(89)], verbose_name='deg')),
                ('dec_m', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(59)], verbose_name='min')),
                ('dec_s', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(59.9999999)], verbose_name='sec')),
                ('dec', models.FloatField(blank=True, null=True, verbose_name='Dec.')),
                ('dec_text', models.CharField(blank=True, max_length=16, null=True, verbose_name='Dec. Text')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('magnitude', models.FloatField(blank=True, null=True, verbose_name='Magnitude')),
                ('color_index', models.FloatField(blank=True, null=True, verbose_name='B-V Color')),
                ('parallax', models.FloatField(blank=True, help_text='mas', null=True, verbose_name='Parallax')),
                ('alias_list', models.CharField(blank=True, help_text='separated by commas', max_length=200, null=True, verbose_name='Alias List')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccultingAsteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='e.g., 2000 CB82 or name', max_length=20, verbose_name='Designation')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number')),
                ('h', models.FloatField(help_text='absolute magnitude', verbose_name='H')),
                ('g', models.FloatField(default=0.15, help_text='slope parameter', verbose_name='G')),
            ],
        ),
    ]
