# Generated by Django 4.0.4 on 2023-12-30 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asteroidoccultation',
            name='asteroid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='science.occultingasteroid'),
        ),
        migrations.AddField(
            model_name='asteroidoccultation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='asteroidoccultation',
            name='path_image',
            field=models.ImageField(blank=True, null=True, upload_to='occ_paths', verbose_name='Path Image'),
        ),
        migrations.AddField(
            model_name='asteroidoccultation',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='science.occultedstar'),
        ),
    ]
