# Generated by Django 4.0.4 on 2023-12-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0002_asteroidoccultation_asteroid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occultingasteroid',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='occultingasteroid',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g., 2000 CB82', max_length=20, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='occultingasteroid',
            name='slug',
            field=models.SlugField(help_text='num--name or num--designation or designation', verbose_name='Slug'),
        ),
    ]
